### ISSUE TITLE
Establish pattern for user account, login, session

### ISSUE THREAD

**Issue by rasmus-storjohann** [pg-irc/pathways-backend#106]
AC: Can create use accounts, set password, log in, log out. This works in local, test and production environments running locally, and in production on Heroku. 

Dead code from [cookiecutter-django](http://cookiecutter-django.readthedocs.io/) (merged in #151) has been cleaned up.

| Environment | Status |
|---|---|
| local on localhost | Can sign up and log in, confirmation URL sent to console |
| test on localhost | Can sign up, confirmation sent by email, which does not work |
| production on localhost | Cannot run server, SSL error |
| test on Travis | |
| production on Heroku | |

**Comment by rasmus-storjohann-PG** [comment]
See 399d4e72a5316ea5ead78e279a02c9d6e030ad0c
