### ISSUE TITLE
Add a mechanism for revisions and change detection of translatable content

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-backend#133]
To efficiently sync translations with an external service (#131), we need to detect if a record has changed since its translations were last exported. So, we should keep track of revision numbers in a standard way.

AC: All translatable records, and records related to HSDS import, have a revision identifier. We can reliably determine if a record has been changed based on that identifier.

**Comment by dylanmccall** [comment]
One excellent tool for this is [django-reversion](https://github.com/etianen/django-reversion), but it is a rather heavy-handed choice and may collide with django-parler.

**Comment by rasmus-storjohann-PG** [comment]
Closing this issue, since the area is not sufficiently well understood to formulate meaningful acceptance criteria. See #149 for more detailed planning of this work,
