### ISSUE TITLE
Service search: full text search

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#165]
See main story #163

Add full text search to the services end point. The user can specify one or more search term for full text search, returned records match the search term anywhere in their text content. Architecture should as far as practicable anticipate that similar search functionality will be added to the organizations and locations end points in the future.

* `/services?search=nice+quiet` returns records that contain "nice" somewhere in any text field, and "quiet" in any text field (boolean AND is implied).
* If no records match, an empty array is returned with status 200
* Giving both taxonomy_term and search arguments as in `/services?search=nice+quiet&taxonomy_term=what:housing` returns records that match both the taxonomic search and the full text search.

**Comment by rasmus-storjohann-PG** [comment]
Note that for "anywhere in their text content" I took that to mean "in name and description". There are various ways to do full text search with both functionality and performance implications, I think it makes most sense to push this change through with the very simple SQL substring query on a couple of fields..

**Comment by bensinjin** [comment]
For this feature I'd probably prefer to see a url like: /services?search=nice+quiet&taxonomy=bc211-what&taxonomy_term=housing. Query seems a little open ended (to me it suggests something more feature rich). I think explicitly setting the taxonomy and the term is more clear - unless the format you've suggested is something being adopted elsewhere?

**Comment by bensinjin** [comment]
Another note - I think a 404 is an odd response for when no records match. To me, the 404 indicates the endpoint your hitting was not found. I would expect an empty array as a response when the search filter(s) return no results.

**Comment by rasmus-storjohann-PG** [comment]
I agree on renaming `query` to `search`, I think I was wanting to adhere to some standard naming, but `search` is clearer, and `fulltextsearch` is too long.
I don't agree on breaking up the taxonomy argument into taxonomy and term queries. I think we will always have more than one taxonomy is the system, so the user will always have to specify which taxonomy they want to use. If we have two queries, it gives the impression that the user is free to use one, the other or both, which is wrong.
I am open to including the taxonomy terms on the service response DTO, but I would hold off on building that until we need it. As to the terminology around this, the HSDS is a bit messy and I raised this issue https://github.com/openreferral/specification/issues/181, we'll see where that goes. I don't think it's a good idea to name things in the database based on what may one day happen at the API. If we need to rename things down the line, I expect that we can, especially in the BC211 end of the DB, where we can always reimport the data so migration is not a concern.

**Comment by rasmus-storjohann-PG** [comment]
You're right on not returning 404, good call!

**Comment by bensinjin** [comment]
Re. the taxonomy terms good points, I agree.
