### ISSUE TITLE
Service search: sort by proximity

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#170]
See main story #163

We assume that the client needs information about services, ranked by the services' respective locations' distance to a reference point provided in the query. There is a many2many relationship between services and locations, meaning that there are many proximity values for a given service. Also, the client is probably interested in information about both the services and the locations. It follows that the return type from this end point should not be an array of Services, but rather a array of objects that contain information from both a service and a location. This leads naturally to a distinct service end point supporting proximity search.

`/services_at_location/` supports proximity sorting as well as all the same filter functionality as `/services/`. However, sorting by proximity and some other field using `sort_by` in the same request is not supported: It does not make sense to sort both by proximity and any other field, since the probability that any two locations will have exactly the same proximity value is low. (Except when multiple services are offered at the same location, hmmm.) This API returns a list of ServiceAtLocation objects that contains data from both the service and location records. 

ACs:
* `/services_at_location/?proximity=-123.456,+23.45`, returns an array of ServiceAtLocation with the service name and location name in the default language
* Support filtering consistent with the `/services/` endpoint: `/services_at_location/?proximity=-123.456,+23.45&search=foobar&taxonomy=foo.bar&page=2&per_page=25`. This will probably involve porting the existing taxonomy work to be a filter
* `/locations/{id}/services_at_location/` returns all the services at a given location, sorting by proximity doesn't make sense in this context, but is it invalid? It's similar to `/locations/{id}/services/` but except that it returns ServiceAtLocation.
* `/services/{id}/services_at_location/?proximity=-123.456,+23.45` returns all the locations for a given service, here sorting by proximity does make sense. It is similar to `/services/{id}/locations/`, except that it returns ServiceAtLocation and supports proximity sort.
* `/locations/{id}/services/{id}/services_at_location/` and `/services/{id}/locations/{id}/services_at_location/` return information about a given service at a given location. It returns one object of type ServiceAtLocation, not an array. It is similar to `/locations/{id}/services/{id}` and `/services/{id}/locations/{id}` except for the return type.

**Comment by bensinjin** [comment]
@rasmus-storjohann Can we just do /services?proximity=49.2827,-123.1207  as the format for these urls? Not sure I understand the $?

**Comment by bensinjin** [comment]
@rasmus-storjohann Please read my essay:

I think we might want to consider changing how we do our proximity filtering for services. 

To implement the proposed solution one strategy is to first sort the locations by proximity and then fetch those location’s associated services. The immediate issue with this approach is the actual list of services, although sorted by proximity, will still show all the locations it references so we’d be at a loss as to what location it came from (I know it’s conceivable that we could sort this list of locations also by proximity but that feels icky). 

Another other approach may be to go from the locations side  of the relationship. A url like locations?proximity=. This approach does make the actual proximity ordering a lot more natural as the lat long values are on the Location object, but we still have an issue when it comes to representing the services at the locations. We’d probably need to provide a mechanism to filter the list by services which is probably work we don’t want to do as I think what I’m proposing may make more sense.

What I’m proposing is we do the ordering on ServiceAtLocation objects. Rename ServiceAtLocation to LocationService (needs to be done at some point, could be done in another issue if it’s not preferable here). Urls should look like location-services?proximity=+49.2827,-123.1207 and results at this endpoint will have a location id, service id as well as any additional fields we think would be useful, personally I’d like to add the point field (new lat long field) from the location so I don’t have to fetch the record’s location to perform the proximity filtering. I think this approach is the cleanest and will be a lot more performant.

**Comment by bensinjin** [comment]
@rasmus-storjohann I think we might want to consider changing how we do our proximity filtering for services. Here's my braindump:

To implement the proposed solution one strategy is to first sort the locations by proximity and then fetch those location’s associated services. The immediate issue with this approach is the actual list of services, although sorted by proximity, will still show all the locations it references so we’d be at a loss as to what location it came from (I know it’s conceivable that we could sort this list of locations also by proximity but that feels icky).

Another other approach may be to go from the locations side of the relationship. A url like locations?proximity=. This approach does make the actual proximity ordering a lot more natural as the lat long values are on the Location object, but we still have an issue when it comes to representing the services at the locations. We’d probably need to provide a mechanism to filter the list by services on the location which is probably work we don’t want to do as I think what I’m proposing may make more sense.

What I’m proposing is we do the ordering on ServiceAtLocation objects. Rename ServiceAtLocation to LocationService (needs to be done at some point, could be done in another issue if it’s not preferable here). Urls should look like location-services?proximity=+49.2827,-123.1207 these urls should also support things like &service_id=12345 to allow further filtering (I think this should just work with our existing filters and the necessary properties on our viewset). Results at this endpoint will have at least a location id and service id as well as any additional fields we think would be useful (might be nice to add service and or location name for filtering). Thoughts?

**Comment by rasmus-storjohann-PG** [comment]
Return a DTO containing service_name and location_name (in English/default language)

Substories:
* AC: The SQL or ORM query to return the data we need
* AC: `/services_at_location/?proximity=-123.456,+23.45`
* AC: `/services_at_location/?proximity=-123.456,+23.45&search=foobar&taxonomy=foo.bar&page=2&per_page=25`
AC: These four work: `/services/{id}/services_at_location/?proximity=-123.456,+23.45`, `/locations/{id}/services_at_location/?proximity=-123.456,+23.45`, `/services/{id}/locations/{id}/services_at_location/?proximity=-123.456,+23.45`, `/locations/{id}/services/{id}/services_at_location/?proximity=-123.456,+23.45`

**Comment by NeilMcKechnie** [comment]
I like the direction you're headed on this @rasmus-storjohann . 

While there may be some use cases for "show my all services close to a specified location" it is probably not the most common one. 

A more practical use case would be something like "I have no money and am currently at this specified location. I need lodging tonight, a job, longer term housing and food assistance." The real need is lack of money and the practical impact is on shelter and food. Proximity is important but eligibility, public transportation, documentation required, hours of operation and a myriad of other factors could make services that are not necessarily close by, the best fit for this person.

So my ideal is a sophisticated search capability that simultaneously spans well-structured data fields in services and locations, and is very aware of the service_at_location links. As far as HSDA is concerned, my need is for the spec to allow for these kinds of sophisticated searches - then it is the job of the software development team to excel at implementing these parameters with high-quality algorithms that yield the best results.

**Comment by rasmus-storjohann-PG** [comment]
QA: 

* `/services_at_location/?proximity=-123.456,+23.45`, returns an array of ServiceAtLocation with the service name and location name in the default language
** PASS
* Support filtering consistent with the `/services/` endpoint: `/services_at_location/?proximity=-123.456,+23.45&search=foobar&taxonomy=foo.bar&page=2&per_page=25`. This will probably involve porting the existing taxonomy work to be a filter
** PASS
* `/locations/{id}/services_at_location/` returns all the services at a given location, sorting by proximity doesn't make sense in this context, but is it invalid? It's similar to `/locations/{id}/services/` but except that it returns ServiceAtLocation.
** PASS but need to figure out how permissive we're going to be for non-sensical requests.
* `/services/{id}/services_at_location/?proximity=-123.456,+23.45` returns all the locations for a given service, here sorting by proximity does make sense. It is similar to `/services/{id}/locations/`, except that it returns ServiceAtLocation and supports proximity sort.
** PASS
* `/locations/{id}/services/{id}/services_at_location/` and `/services/{id}/locations/{id}/services_at_location/` return information about a given service at a given location. It returns one object of type ServiceAtLocation, not an array. It is similar to `/locations/{id}/services/{id}` and `/services/{id}/locations/{id}` except for the return type.
** This AC deviates quite a bit from default DRF behaviour. Need to discuss.

**Comment by rasmus-storjohann-PG** [comment]
I went through the ACs on the story, and found some issues:
* Bug: ServiceAtLocation end point should support proximity sort: It's there in the view set, so it works, but it does not appear in the swagger docs. Expected is that the proximity sort API parameter appears in the swagger docs.
* Bug: Service end point should not support proximity sort, but it's there in the swagger docs. Expected is that the swagger docs for the Services end point does not list the proximity argument
* Bug: See the get_list_schema_decorator() in services/documentation.py: the page_description is not being used. Observed is that swagger docs for the `page` argument is the default help string for this field. Expected is that the more detailed explanation from `page_description` appears for the page argument to *all* end points that accept a `page` argument.

* Suggestion: It could make sense to sort ServiceAtLocation entities by field values as well. Seems to me that that would be easy to add, but we'd need validation so that we don't permit sorting by proximity and a field name. We can do this later or not at all.
* Suggestion: It just makes sense that Locations support proximity sort. It already supports sort by field values, so the same validation logic would be needed. We can do this later or not at all.

**Comment by rasmus-storjohann-PG** [comment]
Also, given that these bugs were introduced in refactoring, there is clearly some unit tests missing, probably in one or more of the `foo_api_tests.py` files.

**Comment by bensinjin** [comment]
Right - is there a sensible way to test our Swagger documentation?

**Comment by rasmus-storjohann-PG** [comment]
And fix commit message "See #170 Clean up Swagger documentation"

**Comment by rasmus-storjohann-PG** [comment]
Getting reeeeeealy close though, feel bad for being so picky.
