### ISSUE TITLE
Document our API using OpenAPI (Swagger)

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#177]
ACs:
* We have the current API documented in the OpenAPI YAML schema
* We have the Swagger or OpenAPI application deployed along with the server

**Comment by bensinjin** [comment]
@rasmus-storjohann this work has been merged however on the PR you mentioned "If you go to https://fierce-ravine-89308-pr-189.herokuapp.com/swagger/ and make a call to /services/ with no argument, you'll see a 500 error." Is this still an issue? If so can we create an issue for it? I'd be happy to have a look when I get a chance.
