### ISSUE TITLE
Lat, long do not appear in the REST response from /locations/ that have NULL for their lat/long point

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#200]
# expected

[Expected](https://coderwall.com/p/gbxelq/simple-rules-for-a-sane-restful-api-design) is that the REST response for a location that does NOT have a location to contain the lat and long fields with the value `null`:

```
{
    "id": "10411983",
    "name": "Dental Clinic",
    "organization_id": "9490502",
    "latitude": null,
    "longitude": null,
    "location_addresses": [
      {
        "address_type": "physical_address",
        "address": {
          "id": 3097,
          "attention": null,
          "address": "605-5050 Kingsway",
          "city": "Burnaby",
          "state_province": "BC",
          "postal_code": null,
          "country": "CA"
        }
      }
    ],
    "description": "Clinic provides low-cost dental health services to individuals (mostly ages 30 and under) who have financial need, and do not have a dentist or dental insurance, or are employed below the poverty line. Services are provided by supervised dental assisting students, dental hygienist, and dentist. Basic services (check-up, x-rays, polishing, fluoride, fissure sealants, oral hygiene, tobacco cessation, and dietary counselling), as related to dental cavities, are free of charge for children and youth ages 19 and under, and $25 for ages 20 and up. Appointments are generally three hours each, with screening and patient records in the first appointment, and teeth cleaning in the second. Fees are charged for tooth whitenings ($75); cash must be paid in advance. Tooth whitening requires three appointments. Clinic operates 8 am to 5 pm Tuesdays. Appointments are required; call for appointments."
  },
```
# observed

Observed is that the REST response does not contain lat and long:

```
{
    "id": "10411983",
    "name": "Dental Clinic",
    "organization_id": "9490502",
    "location_addresses": [
      {
        "address_type": "physical_address",
        "address": {
          "id": 3097,
          "attention": null,
          "address": "605-5050 Kingsway",
          "city": "Burnaby",
          "state_province": "BC",
          "postal_code": null,
          "country": "CA"
        }
      }
    ],
    "description": "Clinic provides low-cost dental health services to individuals (mostly ages 30 and under) who have financial need, and do not have a dentist or dental insurance, or are employed below the poverty line. Services are provided by supervised dental assisting students, dental hygienist, and dentist. Basic services (check-up, x-rays, polishing, fluoride, fissure sealants, oral hygiene, tobacco cessation, and dietary counselling), as related to dental cavities, are free of charge for children and youth ages 19 and under, and $25 for ages 20 and up. Appointments are generally three hours each, with screening and patient records in the first appointment, and teeth cleaning in the second. Fees are charged for tooth whitenings ($75); cash must be paid in advance. Tooth whitening requires three appointments. Clinic operates 8 am to 5 pm Tuesdays. Appointments are required; call for appointments."
  },
```

# getting your bearings in the code

* /human_services/locations/serializers.py defines the fields that are sent over the wire. Lat, long are in there, but for some unknown reason, they are not in the response.
* /human_services/locations/models.py defined the fields as they are stored in the database. 
* human_services/locations/tests/test_api.py should contain new unit tests in `LocationsApiTests` to cover this bug. Suggested TDD approach to fixing bugs: First write one or more test that fail due to the bug, then fix the code so that the tests pass.

**Comment by bensinjin** [comment]
We actually have tests for this: https://github.com/pg-irc/pathways-backend/blob/master/human_services/locations/tests/test_api.py#L115. I actually think this is an issue with the data from the xml not providing lat longs and the api not rendering empty fields. I ran an import locally and noticed missing lat longs but the others displayed their lat longs as expected.  I think I need to re run the import on Heroku. I probably just forgot to after getting all the PostGIS pieces working.

**Comment by rasmus-storjohann-PG** [comment]
Thanks @bensinjin . I dug into it a little bit: So we need to re-import the data on Heroku, because the lat/long coordinates are missing. They were probably dropped by the migration script when we changed how they are represented in the DB. Let's keep that in mind for the future when that kind of problem might bite us harder. Secondly, the JSON should be different for sites that don't have their location, such as `9507266`. I will update this story to reflect what we need there.

**Comment by rasmus-storjohann-PG** [comment]
Closing, cannot reproduce
