### ISSUE TITLE
Task: Build table and read-only REST API

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#206]
### Code style

* Follow existing patterns for unit tests, such as `/pathways-backend/human_services/services/tests/test_models.py` for the model and `/pathways-backend/human_services/services/tests/test_api.py` for the API.
* Use builders to create data structures in the tests. See how `OrganizationBuilder`, `TaxonomyTermBuilder`, `LocationBuilder` and `ServiceBuilder` are being used and implemented.
* Follow existing pattern in `/pathways-backend/human_services/services/` for the new module.

### Module location

Create new django module with path `pathways-backend/tasks`

### Table: tasks

| Name | Type or pattern to follow                                              | Can be null? |
|----------|--------------------------------------------------------------------|------------------|
| id        | `TaxonomyTerm#id`: implicitly defined primary key  |  No                |
| name |  `Service#name`: Translated char field                       | No                 |
| content | Translated text field                                                   | No                 |
| isRecommendedToAllUsers  | bool                                        | No                  |

### Table: user_tasks

| Name         | Type or pattern to follow                                               | Can be null? |
|----------------|----------------------------------------------------------------------|------------------|
| id                 | `TaxonomyTerm#id`: implicitly defined primary key  |  No                |
| user            |  `Service#organization`: foreign key                            |   No               |
| task            |  `Service#organization`: foreign key                            |   No               |
| isInMyPlan  | bool                                                                              | No                  |
| isStarred     | bool                                                                              | No                  |
| isComplete | bool                                                                              | No                  |

### REST calls
Taxonomy terms is left out of the REST responses for this story.

**GET /tasks**
Returns a list of tasks
```json
[
    {
        "id": "12345",
        "name": "the task name",
        "content": "the task content",
        "isRecommendedToAllUsers": false
    },
    {
        "id": "23456",
        "name": "the second task name",
        "content": "the second task content",
        "isRecommendedToAllUsers": false
    }
]
```

**GET /tasks/:taskId**
Non-authenticated call, response:
```json
{
    "id": "12345",
    "name": "the task name",
    "content": "the task content",
    "isRecommendedToAllUsers": false
}
```

**GET /users/:userId/tasks/**
Authenticated call to get the list of tasks for the current user as below

**GET /users/:userId/tasks/:taskId**
Authenticated call, only valid if the userId is equal to the current logged in user's id. Response:
```json
{
    "id": "12345",
    "name": "the task name",
    "content": "the task content",
    "isRecommendedToAllUsers": false,
    "isInMyPlan": false,
    "isStarred": false,
    "isComplete": false
}
```

**Comment by tnightingale** [comment]
This needs to take into consideration localized content; either we have per-locale endpoints or we embed all available text localizations in the appropriate fields. For pg-irc/pathways-frontend#59 I'm proposing we use the latter option as the storage format in the frontend. I think it makes sense to keep the API as similar to this as possible as it will help minimize complexity in the client.

In summary, I'm proposing a type for fields with translatable content that looks like this:
```typescript
interface LocalizedText {
    [code: string]: string
}
```
If the API were to adopt this, its task representation would look like this:
```json
{
    "id": "12345",
    "name": {
        "en": "the task name",
        "ar": "اسم المهمة",
        "zh": "任務名稱"
    },
    "content": {
        "en": "the task content",
        "ar": "محتوى المهمة",
        "zh": "任務內容"
    },
    "isRecommendedToAllUsers": false
}
```

**Comment by rasmus-storjohann-PG** [comment]
@tnightingale Yup, localization will come into play. Before you came on, we did a lot on the search API for the BC211, including (planning) how the locale for the requested data would be done. You can have a look at the search API master story https://github.com/pg-irc/pathways-backend/issues/163 and the localized search (not yet implemented) https://github.com/pg-irc/pathways-backend/issues/173. We would naturally want the `tasks` end point to be consistent with the bc211 endpoints.

**Comment by rasmus-storjohann-PG** [comment]
Also, I should point out that we already have an approach in place for storing multilingual content on the server side using Django parler.

**Comment by rasmus-storjohann-PG** [comment]
Task will not be an entity in our domain anymore. This is a good story as a pattern to follow to define REST endpoints, but other than that, this work is not planned to be completed in this form.
