### ISSUE TITLE
Refactor Newcomers' Guide import script to not depend on Django and PostgeSQL

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#229]
ACs:
 * The Newcomers' Guide data can be converted to TypeScript for inclusion into the client by running a plain python script that does not depend on Django or PostgreSQL
* The Newcomers' Guide data can alternatively be converted to TypeScript for inclusion into the client by invoking a Django manage command as it is currently working. (Once the import script pulls the data into the database, the dependency on Django and PostgreSQL will be there, so no point in breaking it now only in order to have to put it back in in a few months.)

Suggested steps:

* Refactor `/pathways-backend/newcomers_guide/management/commands/import_newcomers_guide.py` to move the content of the `handle()` function to a new file `/pathways-backend/newcomers_guide/import_data.py`. This file should not depend on Django.
* The existing Django-manage `handle()` function should just call the function in `import_data.py`, so that the `manage.py` method of importing the data still works as before.
* Create a new python script `/pathways-backend/newcomers_guide/bin/import.py` that does not depend on Django. Have this script also call the function in `import_data.py`. By running this script, the Newcomers' Guide data can be imported on a system that does not have Django or PostgreSQL installed. Python 3 should be the only dependency.

The tricky part may be logging: The manage script uses `self.stdout` for logging which is supplied from Django, will need to use whatever handle for stdout is available in plain python instead.

**Comment by rasmus-storjohann-PG** [comment]
Hey @trisapeace since you've been blocked on not being able to do the data import under Windows, is this a task you feel like taking on?

**Comment by trisapeace** [comment]
@rasmus-storjohann-PG  
Sure! I won't be able to look at it until after I'm back from holidays (Sept 10) though, so I can't promise it quickly.

**Comment by rasmus-storjohann-PG** [comment]
That's fine, there is no rush on this ... you're really the one who needs it the most ;-)

**Comment by trisapeace** [comment]
Haha, so true. At least... for now. Who knows how many people you'll have working on this by the end :-)
