### ISSUE TITLE
Embed additional data at services_at_location endpoint

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-backend#230]
AC: The fields returned by services_at_location reflect the fields outlined in #197 with the addition of phone numbers added to locations in the following form:
```
    {
        "service": {
           ...
        },
        "location": {
            ...
            "phone_numbers": [
                  {
                      "phone_number_type": "phone1",
                      "phone_number": "+16042681312"
                  },
                  {
                      "phone_number_type": "fax",
                      "phone_number": "+16042930220"
                  }
            ],
        }
    }
```

**Comment by bensinjin** [comment]
TODO define what fields should be returned at services_at_location.

**Comment by bensinjin** [comment]
After we implement phone numbers for locations I'd suggest the services_at_location endpoint exposing the following fields:

*Service fields:*
name, description

*Location fields:*
name, physical_address, phone_number

**Comment by bensinjin** [comment]
See #197.

**Comment by bensinjin** [comment]
This ticket now includes #231.

**Comment by rasmus-storjohann-PG** [comment]
This work was completed under #231
