### ISSUE TITLE
Phone number: tables, fields, and api calls

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-backend#231]
This work needs to be done prior to https://github.com/pg-irc/pathways-backend/issues/230.

ACs:
- Tables implemented for phone numbers
- The importer populates these tables with their associated data from the BC211 dataset

### Table: phone_number_types

|Name|Can be null?
| --- | --- |
id|No

### Table: location_phone_numbers

|Name|Can be null?
| --- | --- |
id|No
location_id|No
phone_number_type_id|No
phone_number|No

## API

No new endpoints. We'll embed this data in the services_at_location endpoint.

**Comment by rasmus-storjohann-PG** [comment]
When you have a table with an id and just one column that is unique, there is room to simplify. The phone number itself already uniquely identifies a phone number record, so the `phone_numbers` table can just be one column. But that can be simplified further to remove the `phone_numbers` table entirely and just put the phone number in the `location_phone_numbers` table, so it's column `phone_number_id` instead becomes just `phone_number`. Makes sense?

Are you sure that a location can only have one phone number of a given type? What if two different employees are both on call in case of emergency? It seems to me that the phone number might be different from address in this case.

**Comment by bensinjin** [comment]
I've updated the spec. I did look at the BC211 data excerpt and from that sample there appears to be one entry for each type under the `<Site>` but I suppose it's possible that constraint does not exist so I've removed it. Using the xml terminology on import I'd expect to parse each `<PhoneNumber>` + `<Type>` pair per `<Phone>` value per `<Site>` for each `<Agency>` I think that's what we want?

**Comment by bensinjin** [comment]
The bc211 dataset has been email, test with it.

**Comment by bensinjin** [comment]
This story now encompasses #197 and #230
