### ISSUE TITLE
Explore TF-IDF approach to matching Newcomers' Guide content to corresponding BC-211 services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#245]
We need some understanding of how the spaCy library may be used to automate the matching of BC211 service provider records to Newcomers' Guide content.

once we have  pg-irc/pathways-frontend#315 merged it will be easy to retrieve the data from the server to assess how the related content calculations are actually performing.

AC: Have one or two threshold value(s) for what is considered relevant for topic-topic relevance and topic-service relevance.

**Comment by svenseeberg** [comment]
If you need some input, I already worked with spacy. Feel free to contact me.

**Comment by rasmus-storjohann-PG** [comment]
I'm sharing office with FlipBoard's NLP guy who has helped me quite a bit to get this going.

**Comment by rasmus-storjohann-PG** [comment]
See [here](https://docs.google.com/spreadsheets/d/1QNl8TCmZgAUXNlF09PrYAOc6hLkIxees2VrJua8-YOg/edit#gid=0) for results.

**Comment by rasmus-storjohann-PG** [comment]
Comments from Aanchan:

Hey Rasmus,
Arti asked me to take a look at the recommendations. I looked at the app, and overall I thought it was really cool!

I went through he code, I understand you are using spacy data structures to represent each document and then using TF-IDF to vectorize the document and the words. 

I noticed related tasks, the "similar/related tasks" results seemed visibly better than "similar/related services".

Assuming that the documents form the rows and the words the columns for the TF-IDF matrix. I am also assuming you are computing cosine similarities between document vectors (i.e. row vectors) is that right?

1. Related tasks : I am assuming Arnie has pointed you to Ben's blog post. At a first glance it looks like weighted TF-IDF or BM25 might give you improvements.
2. Related services: I am assuming you are using document similarities as well? Arti showed a few sample results for "Language assistance". You might notice that the document vectors are likely to look similar because there are some typical words like "services", "information", "working hours" that occur over again in each of the descriptions. The documents are short, for a search term like "Language assistance" ,
 single words like "interpretation",  "interpreters", "language" carry a lot more weight than "information" and "services". Also "language" is often confused for a menopause service for example being offered in multiple languages. So there is a case for disambiguation as well. 
These texts are short too. So there is the case of extremely sparse signal in a lot of noise. The descriptions themselves are not distinguishing enough to pull apart the different services meaningfully. For this scenario, a keyword based search might prove a better strategy. One way could just be a table lookup using a dictionary like data-structure. Another could be to use the column word-vectors vectors  in the TF-IDF martix (instead of row document vectors) to filter out search results. Also are you using the same TF-IDF matrix here that you did for "related tasks"?

You might also consider adding certain terms to your stop words list for a hacky solution to ignore words that you don't want considered while constructing your TF-IDF matrix (in the case that you still want to work with document similarities). These could be words like "information" or "services".

There are a couple of other suggestions I gave Arti about plotting histograms for your scores assuming you could in someway have a histogram of "good recommendation" scores, from the "bad recommendation" scores. For this you would require to have a ground truth of "good recommendations" marked from the "bad recommendations". This should end up giving you a bimodal histogram that looks like this. This could then help you do analysis like Receiver Operating Curves or something that gives you an Equal Error Rate that you can choose as a threshold over your scores. 

Hope some of this helps.
Best,
Aanchan

**Comment by rasmus-storjohann-PG** [comment]
Things to try:
* Remove HTML from services before running through NLP
* Add stop words for "information", "services", etc.

**Comment by rasmus-storjohann-PG** [comment]
Some problems: 
* http://127.0.0.1:8000/v1/tasks/traffic-tickets/related_services/ contains services with any kind of "ticket" mentioned, such as food tickets.
* http://127.0.0.1:8000/v1/tasks/immigration-and-citizenship/related_services/ contains any service funded by Immigration, Refugees and Citizenship Canada
*

**Comment by rasmus-storjohann-PG** [comment]
QA conclusion: TF-IDF is tied with one other algorithm for the best performing, let's use TD-IDF
