### ISSUE TITLE
Server returns bc211 last database update date

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#345]
People often asked how often the Arrival Advisor gets updated data from bc211.
Could we show "Last Update from bc211 database: ______" on the About page of the Arrival Advisor app where we show the app and server version?

**Comment by rasmus-storjohann-PG** [comment]
ACs: * Similar to how the server returns it's version at endpoint /version, return the database version at /dbversion

**Comment by rasmus-storjohann-PG** [comment]
QA: Confirmed that version string for data set is returned from end point `https://fierce-ravine-89308.herokuapp.com/bc211version/`
