### ISSUE TITLE
BC211 import script should return None when provided non-countries.

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#352]
There are five services that have <Country>All Countries</Canada> in their Mailing/Physical Address. 

AC:
- When a non-country is provided, it should return None.

**Comment by tomy-pg** [comment]
Another option is to return N/A. We would need to increase the max character length to 3. Doing NA alone would be misleading as NA is short for Namibia.

**Comment by rasmus-storjohann-PG** [comment]
QA: Checked data imported from source with <Country>All countries</Country> for their mailing address. All these record had valid, complete physical addresses. All affected mailing addresses where dropped on import, as required.
