### ISSUE TITLE
Exclude services below .2 similarity score 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#353]
In Rasmus' review of Jean's QA he found a pattern with the similarity scores. Similarity scores below .2 are bad recommendations, whereas scores above seem to be OK. 

ACs:
* Imported similarity scores include scores above 0.2 only.

**Comment by ArtiBPG** [comment]
Lets hold off on this one till we decide on a better long term plan for evaluations the service listing results
