### ISSUE TITLE
Location on map not correct

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-backend#356]
Description:
User was in Burnaby (probably near: 2101 Holdom Ave, Burnaby, BC V5B 2Z8)
Looked up English classes in Burnaby north, and clicked the map button for one class (not sure which one). The map showed the location in Maple Ridge: https://screencast.com/t/48I2HTdBf

Issue: Service address did not match its location in the map.

This is not enough information to troubleshoot but might expose issues in the data.
Can we find which services lie near the location shown in the map?
Are any of these services English classes? 

Possible reasons for service address not matching location:
- the service has a high simscore but far away from the user showed up?
- The service the user was looking at has lat long in maple ridge but the listed address is burnaby

iOS version: 1.0.8

**Comment by robinpuga** [comment]
I think the lat long is close to 49.217718,-122.6443342

**Comment by tomy-pg** [comment]
Here is how the Address should look:

4180 Lougheed Highway #105

**Comment by rasmus-storjohann-PG** [comment]
This sounds like a classic "we're not the only ones with this issue" problem. Time to hit the google.

**Comment by rasmus-storjohann-PG** [comment]
Suggested solution: Strip suite numbers from addresses before passing them to the maps API.

**Comment by rasmus-storjohann-PG** [comment]
Approach: This is a bug in google maps. Work around is to not include the suite number as the address is passed to google maps. This can be done with a simple regular expression on the client. We still want to show the suite number in our service listing screen.

**Comment by rasmus-storjohann-PG** [comment]
https://www.localsearchforum.com/threads/suite-address-format-a-google-employee-response.45300/

**Comment by jparlina** [comment]
Tested Staging V1.0.23 iOS - fixed (see examples below):

(1) Address 105-4180 Lougheed Highway, Burnaby is now showing the correct location 



(2) When there's no "-" between suite number and street number, Google map shows two options
