### ISSUE TITLE
Need a way to check under which topic(s) a service belongs 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#364]
We received an email from go2hr. Their services are listed in the March 2019 bc211 dataset. However, I couldn't find any of their services under any of the following Education topics or any of the Employment topics on the app:
- Continuing Education for Adults
- Post-secondary education
- Training and certifications to upgrade your qualifications

**Possible solution:**Need a way to check the similarity score of a service corresponding to every topic.
AC:
- Need a way to look up a service using swagger and see its relation to topics (and perhaps locations)to understand why it shows up under a certain a topic related service search.

![Screen Shot 2019-05-02 at 3 47 26 PM](https://user-images.githubusercontent.com/48343061/57111596-9b4ddc00-6cf1-11e9-9bf9-68a3c91c9660.png)

**Comment by rasmus-storjohann-PG** [comment]
Go to staging server https://fierce-ravine-89308.herokuapp.com/swagger/ , navigate to "GET /services/{service_id}/related_topics/", click "Try it out", enter a service id in the "service_id" field, hit "Execute" and see the results in the "Response body" below.
