### ISSUE TITLE
Service Listing: Fix sorting of services

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#374]
When searching for services at locations with user location and topic id, return the services related to the topic and close to the location. Sort the results by a function `f(geoDistance, similarity)`, first stab is `f(geoDistance, similarity) = similarity/geoDistance`.

**Comment by ArtiBPG** [comment]
@rasmus-storjohann-PG is the assumption that the similarity score is a better indication of relevance than the distance? 
Ratio= similarity/distance gives a greater weight to similarity score and lower to distance.

How are services with a  [manual recommendation score of 1 treated?](https://github.com/PeaceGeeksSociety/content/blob/7c7b2f8cdf039a3cbaff000cb7dc1bc43059d363/ManualRecommendations.csv) Does the ratio used the services original similarity score or the manual score 1 assigned to it?

**Comment by rasmus-storjohann-PG** [comment]
> similarity/distance gives a greater weight to similarity score and lower to distance

That is not quite accurate. They both have the same weight, just that larger score makes it rank higher and larger distance makes it rank lower. That's why it's divide.

**Comment by ArtiBPG** [comment]
Need ACs and a better way to QA and track issues, ideally with the QA tool.
Do not push this update to production until the service listing algorithm has been QAed.

**Comment by rasmus-storjohann-PG** [comment]
Agreed.

**Comment by jparlina** [comment]
Tested Staging V1.0.23 on iOS, see example below for topic “Applying for a driver’s license:  the second service listed has nothing to do with driver’s license (BC Centre for Disease Control - GetCheckedOnline)

![E98E6801-CC56-48E5-9812-FF4215E7B772](https://user-images.githubusercontent.com/48343061/60689180-7ac80c80-9e6f-11e9-9f6a-1c376c455f05.jpeg)

![926883AF-AE6B-4F4E-978A-26BBE97329EB](https://user-images.githubusercontent.com/48343061/60689181-7b60a300-9e6f-11e9-8436-bb9e6d358790.jpeg)

![7F31348F-400F-4AFA-9798-22A039BAB596](https://user-images.githubusercontent.com/48343061/60689182-7b60a300-9e6f-11e9-9040-d6ca168c90c7.jpeg)

![C2592457-FF13-4412-AA01-4B4899EE85BB](https://user-images.githubusercontent.com/48343061/60689183-7b60a300-9e6f-11e9-81a2-767c49d08818.jpeg)

![18F3FD5F-A326-49F6-AEC1-9A00B368A3BF](https://user-images.githubusercontent.com/48343061/60689184-7b60a300-9e6f-11e9-9c46-e24b2f8ea125.jpeg)

![D89448D2-ABE4-4BD6-B135-289C0401D554](https://user-images.githubusercontent.com/48343061/60689185-7b60a300-9e6f-11e9-8e1f-cfe092833b01.jpeg)

![17F0398B-3264-4846-8E0A-2CB5655FC514](https://user-images.githubusercontent.com/48343061/60689186-7bf93980-9e6f-11e9-919f-c6cb6b00bd8f.jpeg)

![39C1248B-04D5-4FBC-AFDC-EF1EB1AE1FBE](https://user-images.githubusercontent.com/48343061/60689187-7bf93980-9e6f-11e9-9c4d-0e9fd597d122.jpeg)

![6BE2E582-1EE5-4F10-97A7-48E493225DB7](https://user-images.githubusercontent.com/48343061/60689188-7bf93980-9e6f-11e9-981d-4e6e5536834f.jpeg)

![182C2CBD-CE71-4BF7-BB03-D06E4BD6EDB4](https://user-images.githubusercontent.com/48343061/60689189-7bf93980-9e6f-11e9-87fc-ac30be1539d4.jpeg)

![F293E6D1-23F4-443A-BF00-0904A0660345](https://user-images.githubusercontent.com/48343061/60689190-7bf93980-9e6f-11e9-84fa-d93b56a6d4ba.jpeg)

![2CBB76D2-6130-474A-AEEE-060E6C04CFB8](https://user-images.githubusercontent.com/48343061/60689191-7c91d000-9e6f-11e9-9cb6-c39f84249254.jpeg)

**Comment by jparlina** [comment]
Tested Staging V1.0.23 on iOS - comparing two services with exactly the same description but different addresses. The North Vancouver location (which according to Google Map is further) is listed before the closer Vancouver address.


![IMG_1618.jpeg](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/b346324d-c7a8-4245-816c-fdfbd76f7be1)

![Screen Shot 2019-07-04 at 3.42.12 PM.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/99bdee82-a04d-4fa4-9b5d-a6ae66eea02d)

**Comment by rasmus-storjohann-PG** [comment]
The change from NLP to taxonomies will have affected this functionality, so that it makes sense to test this again before making any additional changes to the code. With NLP, the similarity score for any given service to a given task was a number between 0 and 1, the actual value being the result of the NLP magic. This value was then divided by the distance from the user to the service, and the services ranked by this ratio. Relatively small differences in the NLP score could affect the sorting in ways that would be difficult for users and testers to understand or verify.

Now, with taxonomies, the similarity score is set to 0 or 1, so a service is either related to a topic or it's not, there is no degree of similarity. If the value is 1, then this 1 is again divided by the distance so that nearby services are sorted above distant ones.

**Comment by rasmus-storjohann-PG** [comment]
So @jparlina please have another look at this issue in the current staging app, it may be resolved now.

**Comment by jparlina** [comment]
Now that we are using bc211 taxonomy, this formula is no longer applicable. Closing this issue as per discussion with @ArtiBPG.
