### ISSUE TITLE
BC211 data is throwing required field exception on services that have required field 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#387]
When running import_bc211_data on the 2019-06-13 BC211 data-set there are 4 services that are read as missing <AgencyDescription> even though they do exist. 

The ids of these services are: 9488140, 9488888, 9490254, 9490139. 

If you track these services down in the data-set you will see that they do have Agency Descriptions.![Screen Shot 2019-06-25 at 4.01.04 PM.png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/14735327-4218-49c0-9307-130fa6c69893)

shasum hash to help identify that the data set you are using is the same as mine:  ec20981df523c457dd89925f50e50498c3485738

AC:

- [x] Identify why the AgencyDescription is being read as missing

**Comment by ian-lin-PG** [comment]
Some of the new site Services are missing "Description" tags which raises the exceptions. Consider how nested the data is, Agency -> Site -> Site Services it is not obvious where the exception is raised. I recommend having better error message that includes the Site Service "Key" than using organization ID.

Working on a better error message.

**Comment by ian-lin-PG** [comment]
Issue fixed with the PR for #396 .

**Comment by tomy-pg** [comment]
Server: 1.3.5

This was fixed as part of #396 - did not see required field exception

Steps:
- download june data from S3 bucket

on pathways-backend:
- `./manage.py reset_db`
- `./manage.py migrate`
- `./manage.py import_bc211_data path/to/june/data`
