### ISSUE TITLE
Newcomers guide content: links without http or https are not clickable 

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#390]
Some of the data in the Newcomers Guide links in KO locale are not clickable. 

![Screenshot_20190708-172259_Arrival Advisor](https://user-images.githubusercontent.com/47794846/60850891-132efb80-a1a6-11e9-99f0-bd52e5017db5.jpg)
![Screenshot_20190708-172316_Arrival Advisor](https://user-images.githubusercontent.com/47794846/60850892-132efb80-a1a6-11e9-8777-b302490cfe52.jpg)

AC: 

- [ ] prefix links beginning with www. with https:// 

QA:

- [ ] Go to  the topics _Have your qualifications and credentials assessed_ and _Applying for a driver's licence_ and ensure that the links in the description are clickable

**Comment by ian-lin-PG** [comment]
The reason why the korean language links aren't clickable is because all of the markdown modifiers have been removed during processing. As a result the entire korean translation is basically just pure text.

A related issue in traditional Chinese is that none of the websites have http:// in them which prevents them from converting correctly to links.

Lastly it seems like all the #Headings in Driver lincense page are all gone.

**Comment by rasmus-storjohann-PG** [comment]
Coming up with a regular expressions that detects all URLs is difficult. This is why, when we imported the Newcomers' Guide content, the people doing the importing were instructed to insert `https://` in front of URLs. I guess that instruction wasn't followed always. Using the very rough "URLs start with www" rule will catch many of those slip ups, so it's and OK solution. However, I don't want us to keep going down that route to make that regex increasingly complex and "smart" to catch all URLs. So I would prefer that any URLs that don't have `https://` and don't start with "www" be fixed manually in the content/ repo to have the `https://` prefix.

**Comment by ian-lin-PG** [comment]
In this scenario it would be easy to fix the error manually doing regex replace. Unfortunately, in issue #732 the traditional Chinese translation is much worse. I observed url not terminated properly with a space at the end, thereby absorbing the rest of the sentence as part of the URL. I also seen url that is not prefixed with www. or https:// making it much harder to catch. And in one case the url is split in the middle.

We should probably decide the process on fixing the translation errors. In cases like this where a simple replacement can be done, we could commit the fix ourselves. Or in cases like #732 have translator reevaluate the links.

**Comment by ian-lin-PG** [comment]
We have chose to resolve this issue manually. Related to issue#739

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5

Confirming that the links are clickable.
