### ISSUE TITLE
Blank description field for organization crashes the BC211 import

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#396]
AC:
* The BC211 data dump from June 13 can be imported without crashing the importer

**Comment by ian-lin-PG** [comment]
This issue is related to #387 where missing 'Description' in in ServiceSite is being caught.

**Comment by tomy-pg** [comment]
Server: 1.3.5

Can confirm I can import June data without importer crashing.

Steps:
- download june data from S3 bucket

on pathways-backend:
- `./manage.py reset_db`
- `./manage.py migrate`
- `./manage.py import_bc211_data path/to/june/data`
