### ISSUE TITLE
Do not import inactive data from BC211 data set

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#401]
From Ken @ BC211: "Please make sure to not include inactive records on the Arrival Advisor website.  Inactive records have "Inactive" in the AgencyStatus field as well as "DEL" at the beginning of the agency/service/program description." 

ACs:
* Update bc211 data import script so that it does not import records that are marked as inactive per above. Script located in https://github.com/pg-irc/pathways-backend/tree/master/bc211

**Comment by ian-lin-PG** [comment]
There is no AgencyStatus field as far as I can see, however, a substantial amount of fields have "DEL" within the description.

**Comment by rasmus-storjohann-PG** [comment]
I have emailed Ken for clarification on the missing field.

**Comment by rasmus-storjohann-PG** [comment]
Ken says they would need to do another export for this. I'm concerned that human error on their side will leak confidential information through our app. We need to filter out data marked with DEL to be on the safe side, now it looks like we'll need to do that this week. It's a simple, low risk change.

**Comment by tomy-pg** [comment]
Server: 1.3.5

There are Descriptions that begin with '   DEL'. The script just needs to take into account Descriptions that start with spaces.

**Comment by rasmus-storjohann-PG** [comment]
I'm noticing some records that start with "\tDEL" that are still being imported. This is easy to fiix.

**Comment by rasmus-storjohann-PG** [comment]
Verified that
* Records marked DEL in the XML dump are not included in the database after import, ~10 checked.
* `select * from services_service_translation where description LIKE '%DEL%'; returns no results, same for `locations_location_translation` and `organizations_organization_translation`.
