### ISSUE TITLE
General import script for manually updating recommendations

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#420]
Improve our process for updating service recommendations. Work flow: Import data from iCarol into our database. Export as a spreadsheet optimized for review of recommendations. Edit the spreadsheet by filling in a column with Include/Exclude. Import the data back in from the spreadsheet, so that service recommendations are updated to reflect the Included records only. This story covers the import step.

### Data format assumptions
* Imported data is in CSV format
* There is a column labelled topic_id
* There is a column labelled service_id
* There is a column labelled exclude?

### Acceptance Criteria 
- [x]  For a line in the input spreadsheet where the column labelled "exclude?" has value "Exclude", remove the similarity score records that have the topic_id and service_id from that line.
- [x]  For a line in the input spreadsheet where the column labelled "exclude?" has value "Include", create a similarity score record that have the topic_id and service_id from that line if it did not already exist. Whether the record existed or is created, set the similarity score to 1.0.
- [ ]  It is invalid for a line in the input spreadsheet where the column labelled "exclude?" is empty. Do not change the database, print a error message to the screen and carry on.
- [ ] For every change made to the database, produce log output to the screen. This can be captured and kept as a record of what changes were made.

### Steps for QA: 
1. Populate a database as per our server side deployment process.
1. Create a spreadsheet with columns labelled topic_id, service_id and exclude?
1. Create a few rows in the spreadsheet with topic and service ids that are related per the content in the database.
1. Mark rows as Exclude, Include or blank.
1. Run the script with the spreadsheet as argument, confirm that records are updated as expected.

**Comment by tomy-pg** [comment]
This script was tested and passed QA on the most recent staging release: Client Version 1.5.0, Server Version: 1.3.10.
