### ISSUE TITLE
There are no related topics

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#438]
### Repro steps:
* Build the app without NLP, using taxonomies to relate topics to services
* Open the app and go to any topic details page
* Observe that there are no related topics listed at the bottom of the page
* Expected is that all topics have at least one related topic. 

Before, we used NLP for topic-topic and topic-service recommendations. Now we're using taxonomies for topic-service recommendations, but we're not doing anything to generate topic-topic recommendations.

### Acceptance Criteria 
- [x]  When opening any topic detail page, there is at least one related ("does not look wrong") topic listed as a related topic.

### Notes for QA
- [x] Run the server side prepare deploy script as given in this PR, with --related_services 0
- [x] Run the server side prepare deploy script --related_services 100 or similar to check that it still works with values > 0. This will take longer to run.
- [x] Rerun "./manage.py  import_newcomers_guide ../content/NewcomersGuide/" and confirm that the tasks.ts fixture contains three related topic for each topic.

**Comment by ian-lin-PG** [comment]
Requested @tomy-pg to QA the  --related_services 100 as I keep the taxonomy recommendations for the other taxonomy QA.

**Comment by ian-lin-PG** [comment]
I QAed all the steps, can confirm the new script is working.
