### ISSUE TITLE
CLI for sending notifications to clients

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#442]
### Acceptance Criteria 
- [x] There is a django management command to send notifications to the app. When running the command, the notifications are immediately sent to all devices that have our app installed with permission granted to show notifications.
- [ ] The content of the notification is given in a file, probably in JSON but could be CSV, containing the necessary strings in all locales, as well as configuration of the call to action to be included in the notification.

### Steps for QA: 
1.  Run the command and verify that notifications appear on apps in the correct locale.

**Comment by ian-lin-PG** [comment]
Currently the iOS permission object look as follows which prevents us from setting any notifications.
`Object {
  "expires": "never",
  "permissions": Object {
    "notifications": Object {
      "allowsAlert": false,
      "allowsBadge": false,
      "allowsSound": false,
      "expires": "never",
      "status": "undetermined",
    },
  },
  "status": "undetermined",
}`

**Comment by ian-lin-PG** [comment]
The working android permission object look like this:
```

**Comment by ian-lin-PG** [comment]
Since adding request for iOS permissions, the bug has been resolved.
