### ISSUE TITLE
Services with No Lat Long

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#456]
Based on Sep 16 thread on Slack #pg-product-team, since we use bc211 taxonomy, the recommended services are now sorted by distance instead of similarity score, and are cut off at 25 km max. What do we do with services that have no lat long? 

Example: Under "Community: Volunteering" topic, the service in Whistler appears before the one in Delta (see screenshot). The service is Whistler has no lat long (Service ID53935282) 

![File_001](https://user-images.githubusercontent.com/48343061/65907393-28689000-e379-11e9-91b5-724fc2de815b.png)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.   run the following commands in the pathways-backend repo 
`./utility/prepare_deploy.sh --bc211Path ../bc211/iCarolExport-BC211-AIRSXML-20190613_014810.xml --city_latlongs ../content/city_latlong.csv --newComersGuidePath ../content/NewcomersGuide/ --recommendationsToAddPath ../content/taxonomy/ --outputDir ../`

**Comment by ian-lin-PG** [comment]
Here is the list of services with no latlong https://docs.google.com/spreadsheets/d/1xk3KkoSmiYG_TjSpViMAcvO0_2mDNfDMqnGwp9qUGx0/edit#gid=2112422893
@ArtiBPG please review and close the issue when you think it's complete.

**Comment by ian-lin-PG** [comment]
Out of the 270 services/location without the latlong, the only field that seems to be required is the city. 

I propose that we double check the city within the addresses if the latlong is `NULL` and then use either geocoder or a saved list of city to latlong pairs to add back the latlong at the importer stage. Given that these latlong are inferred instead of known latlongs, appropriate warnings may need to be added to the service listing to indicate as such.

**Comment by tomy-pg** [comment]
QA'd Staging version 1.14.0, Server version 1.3.20:

Under "Community: Volunteering" topic, the service in Whistler still appears before Delta.
I have checked the service and it now does contain a Whistler latitude and longitude. 

While including the cityLatLongs as part of `import_bc211_data`, the script also logged services that did not have latitude and longitude values at the time. 

Will investigate this further.

**Comment by ian-lin-PG** [comment]
The organization here, Whistler Multicultural Network (ID53935282), does not have a latlong but the service does. The service, Peer Immigrant Educator Network (ID54156052), has a latlong of 49.45938, -123.23558 which is no where near Whistler. Google maps show that location is 31km away, but our app uses a straight line between 2 points to calculate distance, so it may fall under 25km after all. Also notice Delta relative to the HiVE could be conceivably further than this wrong latlong.

![image](https://user-images.githubusercontent.com/52009863/71749649-e8f38900-2e2a-11ea-9176-49e4415924e9.png)

**Comment by ian-lin-PG** [comment]
@ArtiBPG @rasmus-storjohann-PG How should we handle this service with the wrong latlong. Should we track services with wrong latlong and forward them to BC211 later?

**Comment by rasmus-storjohann-PG** [comment]
Closed issue, opened #526 to track the one remaining issue.
