### ISSUE TITLE
Bug in Service Listing Sorting Order by Distance (nearest to furthest)

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#465]
@jparlina commented on [Wed Oct 16 2019](https://github.com/pg-irc/pathways-frontend/issues/877)

Tested on iOS 13.1.3 iPhone 7 plus at ISS of BC Welcome Centre - Surrey (10334 152a St, Suite 301, Surrey, BC V3R 7P8) on both: 
- Production V1.7.0; Server V1.3.12; Jun 2019 bc211 data set
- Staging V1.6.0 (same as 1.7.0 in Production); Server V1.3.13; Jun 2019 bc211 data set

_ISS of BC Welcome Centre - Surrey_ shows up as the 24th service of all 30 services listed under the topic _Contact workers at your local settlement agency_ (see screenshots [here](https://docs.google.com/document/d/1Yrq4tR8lcGxLRm4f6spuV4PVMUsuBV0FjZ9EeETSYZk/edit?usp=sharing))

Checked lat/lon using data:
![Screen Shot 2019-10-16 at 3 20 45 PM](https://user-images.githubusercontent.com/48343061/66965866-13a22280-f030-11e9-955b-c3268cf2497c.png)

Checked lat/lon using WiFi:
![Screen Shot 2019-10-16 at 3 20 56 PM](https://user-images.githubusercontent.com/48343061/66965878-2157a800-f030-11e9-8f56-cd6692807664.png)

Checked lat/long on Google Map:
![Screen Shot 2019-10-16 at 3 21 23 PM](https://user-images.githubusercontent.com/48343061/66965891-2fa5c400-f030-11e9-86e2-40f89de33f5c.png)

### Acceptance Criteria 
- [ ]  When searching services from the physical location of office, the service should be at the top or near the top of the service listing, AND 
- [ ]  services should be sorted by distance - i.e. from nearest to furthest from your location

### Steps for QA: 
1.  Select a topic - e.g. Contact workers from your local settlement agency
2. Click "Find related services near me"
3. Services on the service listing should be sorted by distance - i.e. from nearest to furthest from your location

**Comment by rasmus-storjohann-PG** [comment]
The cause of this problem is that the lat/long data for this location is inaccurate in the BC-211 data set. @ArtiBPG I will put this story into triage for reassessment.

**Comment by ArtiBPG** [comment]
BC211 reported that they corrected this. Check with next export from iCarol.

**Comment by ian-lin-PG** [comment]
I just checked the bc211 data and tested with the iOS simulator. Somehow the new latlong is even worse than before. The ISSofBC  Surrey has the id `59807644` and latlong `49.004, -122.7353`. This latlong is so far away from Surrey that it's actually closer to White Rock and close to the US Canada boarder. See the following google maps image of `49.004, -122.7353` for reference:
![image](https://user-images.githubusercontent.com/52009863/81226243-62e57b80-8f9f-11ea-90de-571c445f8220.png)

**Comment by jparlina** [comment]
That's interesting. We actually included the lat long from geocoder in the email that we sent to bc211 about this issue. @rasmus-storjohann-PG Would you check with Ken how bc211 get their lat long data? We found out this issue accidentally when I was at the ISSofBC Welcome Centre Surrey. There might be other incorrect/inaccurate lat long in the bc211 dataset which may affect what show up or not on Arrival Advisor since we use lat long to show "services near me".

**Comment by rasmus-storjohann-PG** [comment]
So for reference, the correct lat/long is 49.190122,-122.7995352, see [here](https://www.google.com/maps/place/ISSofBC+Welcome+Centre+-+Surrey/@49.190122,-122.7995352,19z/data=!4m5!3m4!1s0x5486714bfd1bd12b:0x7db8be7b28f18dc9!8m2!3d49.19011!4d-122.7990121)

**Comment by jparlina** [comment]
[Here](https://drive.google.com/file/d/1ccX6fmptMuFLDwjxD_Re7pGC0798Lo92/view?usp=sharing)'s the email that we sent bc211 last Nov and the [list of special cases/issues](https://docs.google.com/document/d/1YmrqUW4Gni3p2HMIXLatIBwvjBNltRWQNMi5eABpNJk/edit?usp=sharing) we discovered in the bc211 dataset. I thought the lat long that I emailed them was from geocoder, but it's different from what @rasmus-storjohann-PG has in the comment above. 

@rasmus-storjohann-PG @ian-lin-PG Could we do some random check of the lat long of some service records in the bc211 dataset to see if they are accurate or totally off. If this was the only one with incorrect lat long then we can email them again to fix the lat long. But if there is a bigger issue with the lat long of bc211 service records, then we need to ask how they determine their lat long, and what they or we need to do to fix them for AA.

**Comment by rasmus-storjohann-PG** [comment]
See #pg-irc/pathways-frontend/1042 for a possible approach to solving this problem

**Comment by jparlina** [comment]
Thanks for looking into this. @ian-lin-PG. 
@rasmus-storjohann-PG It's worth asking Ken at bc211 how they get their lat long as our next step so we can figure out how to fix this issue.

**Comment by rasmus-storjohann-PG** [comment]
"ISS of BC Welcome Centre - Surrey" has the wrong lat/long in the BC211 data set, this is apparent from [this page](http://redbookonline.bc211.ca/service/59807644_59807644/issofbc_welcome_centre___surrey?search1=ISSofBC%20Welcome%20Centre%20&search2_basic=surrey&from=NDkuMTA0NDMwMiwtMTIyLjgwMTA5NA==) on BC211's site.

**Comment by rasmus-storjohann-PG** [comment]
This is not something we can fix, it's really BC211's data error to fix. If we get into fixing these kinds of issue, our deployment process will become too complex. Moving this issue back to the backlog to keep an eye on it.

**Comment by jparlina** [comment]
Notified bc211 of the incorrect lat long via email to updates@bc211.ca on Oct 13, 2020.

**Comment by rasmus-storjohann-PG** [comment]
We should ask for a dataset from BC211 on Oct 19 which will be used in the next release.

**Comment by rasmus-storjohann-PG** [comment]
Next step: Review this data in the latest dataset from BC211 to determine if it has been fixed

**Comment by ian-lin-PG** [comment]
@jparlina ISSofBC is now the 11th service to show up Contact settle worker in Surrey. BC211 has used the latlong you have provided.

**Comment by tomy-pg** [comment]
Co-signed with what Ian stated.

**Comment by jparlina** [comment]
Tested on Staging v1.61.0, server v1.3.50 using Easter egg "Custom 49.190194, -122.799250" (the org's lat long) then did topic search "Contact workers at your local settlement agency", result: ISSofBC Welcome Centre Surrey was the first result.
