### ISSUE TITLE
Include phone number data in algolia data

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#479]
Currently the phone number data is not included in the data served from Algolia. 

We won't be able to do just one query against the DB to get the data for algolia, we need to do at least two and do some post processing to get the phone number data in htere. The processing will probably happen with JSON data, not CSV data, but either could be used.

### Acceptance Criteria 
- [x]  The phone number data is included

### Steps for QA: 
1.  Make a search through the app or through the algolia web interface, see that phone numbers are there.

**Comment by jparlina** [comment]
Phone numbers show up on Algolia and match bc211 data - tested for the following services:
- Settlement and Integration Services provided by Jewish Family Services (service ID: 14461389)
- Migrant Workers Centre (service ID: 9488189)
- Settlement Workers in Schools (SWIS) Program by Burnaby School District (service ID: 9508423)
