### ISSUE TITLE
Load BC211 data incrementally

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#490]
Updating our database with new data from BC211 may cause new records to be created, existing records to be changed, or existing records to be deleted. It is assumed that record are uniquely identified by their primary keys as assigned by BC211.

Primary entities (primary keys assigned by BC211) subject to create, update or delete:
* organization (Agency)
    * location (Site)
        * address
        * phone number
        * service (SiteService)
            * service_at_location
            * taxonomy term

Secondary entities (primary keys not assigned by BC211) that may be subject to create or delete related to changes in primary entities:
* address
* addresstype (probably not)
* locationaddress
* serviceatlocation
* phoneatlocation
* phonenumbertype       
* service_taxonomy_terms         
* taxonomies_taxonomyterm                 

### Create Agency, Site, SiteService

Input contains records with primary keys that don't already exist. 

- [ ] New records are created. 
- [ ] New secondary records are created holding the addresses, phone number, etc. 
- [ ] Logs indicate that a record with the given type, primary key and name was created. 
- [ ] Debug logs indicate that secondary records with the given content was created.
- [ ] Do not import records marked `DEL` as per BC211 convention for inactive records.

### Delete Agency, Site, SiteService

Input does not contain records with primary keys that already exist in the database. 

- [ ] A temporary table is populated with all ids from the input data, so that we can query at the end and find the records that are there in the database and not in the input. 
- [x] Existing records are deleted 
- [ ] Secondary records holding addresses, phone numbers, etc. are deleted too. Use psql cascading deletes to implement this? 
- [ ] Logs indicate that records with the given types, primary keys and names were deleted. 
- [ ] Debug logs indicate that secondary records with the given content were deleted.
- [ ] Temporary table is dropped at completion
- [ ] Records marked `DEL` as per BC-211 convention for inactive records are also deleted.

### Update Agency, Site, SiteService primary records

The changed field being part of the organization, location or service table: 

- [x] Existing records are updated to reflect the changed data. 
- [ ] Logs indicate that records with the given types, primary keys and names were updated.

### Update secondary tables

The changed field being part of secondary tables like address or phone number: 

- [x] Existing secondary records are deleted. Use cascading delete to implement this? 
- [x] New secondary records are created. 
- [ ] Logs indicate that secondary records related to records with given types, primary keys and names were updated.

### Other changes

- [ ] Add column `data_owner` to primary tables, populate with "BC211" for data from BC-211.
- [ ] Add `created_at` and `updated_at` columns to all tables

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG I recommend creating a new django command that clears the bc211 tables before importing bc211 data. This should preserve other tables that shouldn't be reset after each bc211 import. Specific functions clearing out each bc211 table should be easily unit testable, and remove the need to archive important tables that gets flushed with the current release process.

**Comment by tomy-pg** [comment]
@ian-lin-PG I think this would be nice to have and this would remove some of the manual work we have been doing with psql after putting up a release. However, I still see the value in taking production database backups incase of emergencies.
