### ISSUE TITLE
Server side: Dynamic content on the home page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#527]
[This is the client side issue](https://github.com/pg-irc/pathways-frontend/issues/1151).

- [x] We have a new Django app called "content", which contains the following:
- [x] We have a database table for alerts
- [x] Each alert has a heading (localized), a content string (localized) and an id. Localized strings are managed using `TranslatedFields` from `django.parler`, following the pattern in the services table.
- [ ] We can use the Django admin console (web interface) to maintain the content of the table, including localized strings.
- [x] A GET request to /alerts/{locale} returns a list of zero or more alerts in the given locale
- [x] A GET request to /alerts/{locale}/{id} returns the alert with the given id in the given locale
- [x] PUT, POST, DELETE are not supported on these end points
- [ ] Populate the table with data identical to the current COVID-19 card in the app. This is here to demonstrate that the feature works, using a development server install. Populating this table in staging or production is out of scope for this story.

**Comment by niko-pg** [comment]
Hi all, I've started working on this. As of writing, my working model has the following attributes:

```
class Alert(ValidateOnSaveMixin, TranslatableModel):
   id = RequiredCharField(primary_key=True,
                           max_length=200,
                           validators=[validators.validate_slug])

  translations = TranslatedFields(title=models.CharField(max_length=200),
                                    content=models.TextField(blank=True, null=True))
```

Do you have any preliminary thoughts on this @rasmus-storjohann-PG ? I was thinking maybe it should be related to a taxonomy/topic, but in the spirit of "simplify", I didn't consider it for now.

**Comment by rasmus-storjohann-PG** [comment]
@niko-pg note that there's a bit of work left to complete on this story.

**Comment by rasmus-storjohann-PG** [comment]
Sorry, I only saw your questions now, 10 days later. Sorry about that.

All the answers to your questions are in the story, though. If I wanted additional columns I would have spelled that out. Also, the names of the columns were specified but you used different names. So the short answer is really, if it's not specified in the story, then it's out of scope for the PR.

**Comment by rasmus-storjohann-PG** [comment]
I was also working with the PR a bit to adjust naming, so in the end the URLs are a little bit different from the spec. I usually find that finalizing naming needs to be hands on with the code.

Hope this makes sense, we can discuss if you like.

**Comment by tomy-pg** [comment]
Staging version 1.35.0: PASS
