### ISSUE TITLE
Simplified and Traditional Chinese Content-alert are using the same server content

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#543]
When content alerts are loaded onto our app, we notice that the strings for Simplified and Traditional Chinese are the same even though they are different on the database. 

The front-end and the back-end use different language codes to identify Simplified and Traditional Chinese. 
**Front-end**:
Simplified Chinese - `zh_CN`
Traditional Chinese - `zh_TW`

**Back-end**
simplified Chinese - `zh-hans`
traditional Chinese - `zh-hant`

Through some debugging, it appears that the front-end pulls the server content from`zh-hans` for both `zh_CN` and `zh_TW`. 

The server should accept both variations of the locale codes described above.

### Acceptance Criteria 
- [x]  When Traditional Chinese is selected on the app, it receives the Traditional Chinese content alerts from the server
- [x] When Simplified Chinese is selected on the app, it receives the Simplified Chinese content alerts from the server

### Steps for QA: 
1.  Populate your local `pathways_local` database with content alerts - be ensure to include rows for `zh-hans` and `zh-hant`.
2. Run your local server and open up swagger
3. Try out the GET request for `/v1/content/alerts/{locale}/` using `zh_TW` as your locale. This is the locale code for Traditional Chinese used by the client.
- [x] Ensure that you receive the content alert for Traditional Chinese - `zh-hant`

**Comment by ian-lin-PG** [comment]
Pass QA at 1.42.0
