### ISSUE TITLE
Unable to add content-alert on Admin for Tagalog locale (can work-around with Postico)

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#548]
When trying to add a content-alert via Django admin, I receive this error:
![Screen Shot 2020-08-24 at 11.50.41 AM.png](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/4711ad98-7095-4273-9c2c-119955ed67d3)

### Acceptance Criteria 
- [ ]  Tagalog content alerts should be able to be produced on Django Admin

### Steps for QA: 
1.  Log into django admin
2. Add a content alert for tagalog 
- [ ] Content alert should be successfully created
4. Use swagger to look for tagalog content alert created

**Comment by rasmus-storjohann-PG** [comment]
This should be fixed, but time box it if it's really complicated we can live with the work around of using Postico

**Comment by rasmus-storjohann-PG** [comment]
- [ ] Document this is the appropriate GitHub README

**Comment by rasmus-storjohann-PG** [comment]
This is a Django problem with a work around, closing as won't-fix
