### ISSUE TITLE
Support more than one API key

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#549]
Currently we only support one API key, so we can not easily change the API key without affecting the behaviour of the older versions of the app. 

### Acceptance Criteria 
- [x]  There is a table containing the set of valid API keys
- [x] We can have more than one valid API key by adding more rows to the table

### Steps for QA
- [ ] Get the server running on Heroku as a review app with the code from the PR
- [ ] Connect to the DB on Heroku and add one or two entries to the api keys table
- [ ] From Postico or similar, post a new push notification token, including in the request a valid API key as entered in the table. Confirm that this succeeds and the token is added to the table.
- [ ] Do the same again but with an invalid API key, so one that does not appear in the table. Confirm that this fails and the token is not added to the table.

**Comment by tomy-pg** [comment]
@rasmus-storjohann-PG how would you like this QA'd?

**Comment by tomy-pg** [comment]
Looks good
