### ISSUE TITLE
Pull in push notification tokens from DB backups

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#554]
Push notification tokens are deleted as part of our normal release process. We have old ones in production server backups.

### Acceptance Criteria 
- [ ]  Restore the push notification tokens from backups to the current production database.

See also #553 which fixes the underlying problem.

**Comment by tomy-pg** [comment]
Please review the process below:

1. Restore the August 31 DB backup `pg_restore --verbose --clean --no-acl --no-owner -h localhost -U `whoami` -d pathways_local ~/Downloads/pathways-production-backup-2020-08-31.psql-db-dump 
`
2. Copy push notification tokens into a csv:
```
psql -d pathways_local
\copy push_notifications_pushnotificationtoken TO ~/Desktop/push_notifications_pushnotificationtoken_backups/2020-08-31/push_notifications.csv;
```

3. On production database, create temporary table with August 31 push notifications:
```
psql -d PROD SERVER

CREATE TEMP TABLE tmp_table                                                                                                    
AS
SELECT * 
FROM push_notifications_pushnotificationtoken
WITH NO DATA;

\copy tmp_table FROM ~/Desktop/push_notifications_pushnotificationtoken_backups/2020-08-31/push_notifications.csv;
```

4. Insert data from temporary table to `push_notifications_pushnotificiationtoken`:
```
INSERT INTO push_notifications_pushnotificationtoken
SELECT DISTINCT ON (id) *
FROM tmp_table
ORDER BY (id)
ON CONFLICT DO NOTHING;
```

5. Drop temporary table"
```
DROP TABLE tmp_table;
```

**Comment by ian-lin-PG** [comment]
I approve what @tomy-pg has for adding back old notification tokens. I think we can use a modified step 3 and step 4 for archiving and restoring notification tokens along with content alerts like we do with staging.
