### ISSUE TITLE
Import BC211 CSV data dump

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#557]
Questions about the input data:
* Are all the data column names unique? (Can we use the column headers as identifiers) Yes, they are unique.

Requirement:
* Avoid solutions that require holding all the data in memory at one time. I.e. the space requirement should be O(1).
* Input CSV data may not have service ids, output must have service ids, the same service imported multiple times must get the same id each time.
- [ ] Do not include inactive records!!!
- [ ] Ensure that BC211 taxonomy ids what, who and why are carried through to the taxonomy terms CSV output, so that we end up with data like this:
 
 id  | taxonomy_id |              name              
-----|-------------|--------------------------------
   1 | airs        | nd-3500
   4 | bc211-what  | employment-search-assistance
   5 | bc211-why   | disability-mental-health
  16 | bc211-who   | youth

from Tomy:
```
The taxonomy terms in the csv files can be distinguished by -
What - all uppercase
Why - all lower case
Who - begins with uppercase
Asterisk (*) separates grouped taxonomy terms
Semi-colon(;) separates groups
```

Possible approaches
* Write separate tool to convert single giant CSV file into OpenReferral compliant CSV files, one per entity, then import the standards compliant files. The import step will be simple and enable future imports of standard compliant files from elsewhere.
* Write code to parse the separate files and return the same data structure as `parser#parse_agency`, so that the importer can be left unchanged. 
* This is a little tricky since the design is coupled to the nested structure of the XML format, which is different from the non-nested CSV format. Possible refactor is to move the calls to `parse_sites()` and `parse_service_list()` to `update_all_organizations()`, not a trivial change...
* We could try to order all the CSV files by their organization ids, so that we can maintain the same order of parsing all files to match what happens when parsing the XML. The importer needs to be able to detect and error out when the other files are out of order, they do not need to support importing from out of order.
* Phone and address record ids are trickier as pointed out by @ian-lin-PG below.
* Can all the CSV files be arranged so that a simple command line sort-tool can be used to create the correct ordering of these files? This would amount to simply put the organization id at the start of the line, or (not as smooth) put them at a fixed, well known column offset using sort -k.
~* Import one row at a time, writing to all the relevant tables one at a time. The import step will be more complicated.~
~* Import one row at a time, writing to one table, i.e. read the input file several times. Simpler, but less performant.~

**Comment by ian-lin-PG** [comment]
Ian's 2 cents.
* Each row now contains a service OR an organization, this allow us to have just as granular of detailed information for organization as we do services. This includes taxnomy data, latlong.
* There are much more columns than we need in the app. We can preprocess and remove the extra columns so the import might be faster, at least it takes less memory to store an entry. This might be relevant when validating the CSV file to be OpenReferral compliant.
* I definitely prefer processing entry by entry and writing to multiple tables per entry. 
* Overall I am most concerned about the addresses and phone number table which we assign our own IDs than services and organizations with given unique IDs.

**Comment by tomy-pg** [comment]
All the data column names are unique:
`head -1 bc211-data-20200924.csv | sed -e $'s/,/\\\n/g' | wc -l` - 73
` head -1 bc211-data-20200924.csv | sed -e $'s/,/\\\n/g' | uniq -i | wc -l` - 73

**Comment by rasmus-storjohann-PG** [comment]
Ensure that BC211 taxonomy ids what, who and why are carried through to the taxonomy terms CSV output, so that we end up with data like this:
 
 id  | taxonomy_id |              name              
-----|-------------|--------------------------------
   1 | airs        | nd-3500
   4 | bc211-what  | employment-search-assistance
   5 | bc211-why   | disability-mental-health
  16 | bc211-who   | youth

**Comment by rasmus-storjohann-PG** [comment]
Steps for QA, @ian-lin-PG and @tomy-pg 
* Import the data into a staging server
* Export the data for algolia and import it into a staging index in Algolia
* Select a dozen different records from the BC211 input CSV data
* Look the corresponding data up from algolia and double check that the data is accurage.
* Look the corresponding records up in the server by hitting the service_at_location REST end point and compare the data
* Once we have the staging app built with the new code, look the services up in the app and double check the data in the app with the data in the BC211 CSV data dump

**Comment by rasmus-storjohann-PG** [comment]
This work in Django is no longer relevant, we are using Mongo to do this.
