### ISSUE TITLE
Add AlternateName field from bc211 dataset & need to be searchable

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#566]
We received [feedback](https://docs.google.com/forms/d/11J_1pg03O83unmx2_UmVoAPQ1o0xnbKYMgTSUDJYGO0/edit?entry.2078767010=English+Demo+-+Sep+15#responses) from the recent online demo that "Societe de Developpement Economique Columbie-Brittannique (SDECB)" can't be found anywhere on AA: "I have been working with Bc211 to promote SDECB service. I still don’t understand how to to fin that on your app. Lot to do in French. Pretty disappointed Canada is a bilingual (French speaking) country"
It is listed on [bc211 website](http://redbookonline.bc211.ca/organization/63085405/economic_development_society_of_bc_edsbc?search1=Société%20de%20développement%20économique%20de%20la%20Colombie-Britannique&search2_basic=&).

**Acceptance criteria**
- [ ] Update our CSV files used to build the app to make sure that the EDSBC appears under Francophone settlement services.
- [x] Importer includes AlternateName when importing from BC211 CSV files services and organizations
- [x] Importer includes AlternateName when importing from OpenReferral CSV files for services and organizations
- [x] Alternate name columns appear as part of the service and organization database tables
- [x] Client shows alternate name in Service detail and Organization detail pages when available
- [x] Alternate name is included in the data on Algolia, so we can find services by searching for their alternate name

**Two issues:**
1. The French name is under "AlternateName" field in the [bc211 data set](https://docs.google.com/spreadsheets/d/1qEX4eTYLoSW7xLahgEyYecZe3Jl-E2Z1YH_Y7nd7x9Q/edit?usp=sharing_eil&ts=5f6d26cc) and AA only includes "PublicName". I was able to search only the English name "Economic Development Society of BC (EDSBC)" using the search function. 

![Screen Shot 2020-10-15 at 4 23 11 PM](https://user-images.githubusercontent.com/48343061/96196031-35640d00-0f03-11eb-840f-017eb84661b2.png)

2.  Why does "Economic Development Society of BC (EDSBC) (aka Societe de Developpement Economique Columbie-Brittannique (SDECB))" not appear under topic "Francophone settlement services"? It's not listed in [csv used for topic search ](https://docs.google.com/spreadsheets/d/1CSNCvpNwqX8VnxGESbcKOo_nlhcINZHXhrmCPyyvBXQ/edit#gid=2061482737)although it has the [taxonomy "who:french"](https://docs.google.com/spreadsheets/d/1NsddiMqRW9fEh3QgM9119kfqLIcxT0Fez9TP83qXYn8/edit#gid=1069225144). Is this a case of Org without services? But how come I was able to find the English name using search function?

![Screen Shot 2020-10-15 at 4 23 57 PM](https://user-images.githubusercontent.com/48343061/96196609-a48e3100-0f04-11eb-862b-af99f26ad47d.png)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Server side work is being completed as part of #564

**Comment by ian-lin-PG** [comment]
I just noticed that this is an organization without services, an alternate service was not created to be imported into algolia it seems.

**Comment by jparlina** [comment]
@ian-lin-PG We will need to review organization records without services ([issue #1335](https://github.com/pg-irc/pathways-frontend/issues/1335)) once you have the list and decide the best way of showing org records moving forward. Currently we only decided to create a service record by duplicating the bc211 org record for public libraries, community centres, school districts. But these were temporary/band-aid solutions. 

Having said that, we still need to add "Alternate Name" field (as described in this issue) for all existing records so they are searchable.

**Comment by ian-lin-PG** [comment]
@jparlina this particular service seemed to have been removed. I found another service that uses alternate name. `911 Cell Phone Program` has the alternate name `old name Priority Response Partnership (Cell Phone/Home Alarm Program)`. Searching for `Priority Response Partnership` on the app shows `911 Cell Phone Program` as one of the search results.

**Comment by jparlina** [comment]
@ian-lin-PG Societe de Developpement Economique Columbie-Brittannique (with alternate name Societe de Developpement Economique Columbie-Brittannique (SDECB)) is listed on [the latest bc211 csv 20210114](https://docs.google.com/spreadsheets/d/1uQstmABhIqCoKRlord8FmgrJSYQHph5oJEoZrgZM0k4/edit#gid=502040760)

- This is one of the organization record with no services. Once organizations with no services are fixed (can be shown on AA), then we will need to also connect this record to ""Francophone settlement services" topic. 
- Search function in general (not just for this service) should search both "Public Name" and "Alternate Name"

**Comment by ian-lin-PG** [comment]
This particular service shows up.
![image](https://user-images.githubusercontent.com/52009863/108553342-61bfd980-72a7-11eb-9e3c-d7b3344fd4cc.png)

**Comment by rasmus-storjohann-PG** [comment]
This issue is not done:
- [ ] Change the client so that the alternate name shows up in the service detail screen
- [ ] Update the mongo processing pipeline to ensure that the alternate name appears in the data to be sent to algolia

**Comment by cherrielam** [comment]
- EDSBC **does not** show up for me under the Francophone Settlement Services topic in Staging 1.74, iPhone XS, searching from My Location (Fairview) and using "Vancouver" search term
- Alternate name does show now on services, but could we change the copy on the app from "alternate name" (lowercase) to "Alternate name" (uppercase A)

**Comment by brandon-PG** [comment]
This feature is working as intended. To test try searching 'First Step Addictions Services' in Kamloops, BC. It will return the intended service

**Comment by alysha-PG** [comment]
EDSBC does not show up for me under the Francophone Settlement Services topic in Staging 1.85, iPhone, searching from My Location (Vancouver)

**Comment by brandon-PG** [comment]
> This feature is working as intended. To test try searching 'First Step Addictions Services' in Kamloops, BC. It will return the intended service

@alysha-PG The EDSBC service gets filtered out in the mongo process. Try this search term instead.

**Comment by alysha-PG** [comment]
ESDBC doesn't show up because it's a parent agency and not a service.
