### ISSUE TITLE
Progress indicator on the push notification command line tool

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#571]
Sending push notifications is a bit slow, it would be nice if the tool showed progress as it was going through the list of recipients. It would allow us to detect any kind of throttling, etc.

### Acceptance Criteria 
- [ ]  The script shows progress with dots or similar.

**Comment by tomy-pg** [comment]
Tried this on Staging version 1.55.0: PASS
