### ISSUE TITLE
Location filter under Topic Search not working properly

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#574]
When reviewing school district and Settlement Workers in Schools (SWIS) data, I found the following issues under topic search “Registering your child in a public school”:

- Abbotsford SWIS (service ID 9508538) did not show up when I entered “Abbotsford” in the location field. But it showed up when I entered “Langley” although the address and lat long are in Abbotsford. See screenshots below. 

AC:
- [ ] Identify the problem and discuss before proceeding with a solution

![Screen Shot 2020-11-17 at 12 11 25 PM](https://user-images.githubusercontent.com/48343061/99442397-2ab7e180-28ce-11eb-84f5-caf875c49600.png)

- Delta SWIS (service ID 9508525) did not show up when I entered “Delta” in the location field”. However, it showed up when I selected “My location” (Burnaby) even though the address and lat long are both in Delta. See screenshots below. 

![Screen Shot 2020-11-17 at 12 09 27 PM](https://user-images.githubusercontent.com/48343061/99442223-e4fb1900-28cd-11eb-8fd0-6f41ee154a58.png)

This issue is not limited to certain topics and/or locations. Tested on topic "Contact workers at your local settlement agency" - the topic search results listed services in North Vancouver; however, when I entered "North Vancouver" in the location field, the results were "No services to show". See screenshots below. 
![Screen Shot 2020-11-17 at 4 54 34 PM](https://user-images.githubusercontent.com/48343061/99468660-e04a5b00-28f5-11eb-8988-e9ab9f262e75.png)

### Acceptance Criteria 
- [ ]  Location field under Topic Search should properly filter topic search results by location entered by users

### Steps for QA: 
1.  Go to Learn page - select "Things to do right away" - select "Registering your child in a public school"
2. Click "Find related services near me"
3. Enter "Abbotsford" in the location field
- [ ] you should find Archway Community Services - Settlement Workers in Schools (SWIS) Program with Abbotsford address in the search result
4. Enter "Delta" in the location field
- [ ] you should find Delta School District - Settlement Workers in Schools (SWIS) Program with Delta address in the search result

**Comment by rasmus-storjohann-PG** [comment]
Looks like there's an Abbotsford in Wisconsin that is returned from geocoder.

The suggested solution to this is to show the "Wisconsin" bit in the search result so users know to refine the location

**Comment by jparlina** [comment]
As the screenshots above show, the issue is not limited to "Abbotsford".

**Comment by rasmus-storjohann-PG** [comment]
Suggested solution: 
* Make the geocoder request with the string as supplied by the user
* If the return is for a location that is not in BC, repeat the request with "BC" appended to the search term
* If the return is for a location in BC, use that instead
* In any case, show the province/state on the screen as part of the "Near Nelson BC" string.

**Comment by tomy-pg** [comment]
Staging 1.54 - PASS
