### ISSUE TITLE
Handle organizations when they are offline

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#581]
Similar to search and topic services the organizations component and service for organizations component need to have error screens for when users are offline and exception.

### Acceptance Criteria 
An error screen exists for situations when:
- [ ] Users are offline
- [ ] An exception occurs

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
Issue moved to [pg-irc/pathways-frontend #1323](https://github.com/pg-irc/pathways-frontend/issues/1323) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rasmus-storjohann-PG** [comment]
Closed, see https://github.com/pg-irc/pathways-frontend/issues/1323
