### ISSUE TITLE
As an End User, I can find service information in my native language.

### ISSUE THREAD

**Issue by robinpuga** [pg-irc/pathways-backend#59]
We want Services Advisor Pathways to support multilingual capabilities to allow users who do no know English to still benefit from the application.

One big challenge of this is that we are operating from an existing data source (BC211 records). These records have not (to our knowledge) been translated previously so there will be a massive effort to get these translated.

**Questions:**
- Number of languages we will support for translations
- Number of source languages the content can be in
- How the translation process will be managed
- How the translation process will be staffed (Volunteers? Translation contractors?)
- What technologies can we leverage (Google translate, Transifex, etc)

**Comment by tuckerbuchy** [comment]
This relates to the requirement for Services Advisor Pathways to be multilingual. 
We need to define to scope of what this really means.
Can we come up with answers for these:
* Number of languages we will support for translations
* Number of source languages the content can be in
* How the translation process will be managed
* How the translation process will be staffed (Volunteers? Translation contractors?)
* What technologies can we leverage (Google translate, Transifex, etc)
