### ISSUE TITLE
Server Error on some topics - Staging 1.57.0

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#591]
"Server error" (see screenshot below) when clicking "Find related services near me" on Staging V1.57.0, Server V1.3.46 for some topics such as:
- Contact workers at your local settlement agency
- Community and recreation centres
- Registering your child in a public school
- Continuing education for adults
- Adults completing secondary school
- Early years programs for children under five years of age
- etc

![Image from iOS.png](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/71a9a9a4-5c63-4a88-9446-fcc0741788dc)

### Acceptance Criteria 
- [x]  Clicking "Find related services near me" should show a list of related services instead of "Server error"

### Steps for QA: 
1.  Select one of the topics listed above 
2. Click "Find related services near me"
3. You should see a list of related services instead of "Server error"
4. Test for more than one topics (repeat steps 1-3 for different topics)

**Comment by tomy-pg** [comment]
The `topicServices` json from the server is failing AJV validation. In particular, I see that `addresses[0].address.city` fails.
Log from ajv error:
```
data[3].location.addresses[0].address.city should be string
```

**Comment by ian-lin-PG** [comment]
Failed QA 1.59.0, `Registering your child in a public school` has services, but the rest of the topics return server errors again.

**Comment by tomy-pg** [comment]
`Adults completing secondary school` has services

**Comment by tomy-pg** [comment]
```
Contact workers at your local settlement agency - data[15].service.name should be string
Community and recreation centres data[4].service.name should be string
Continuing education for adults data[9].service.name should be string
Early years programs for children under five years of age data[13].service.name should be string
```

**Comment by ian-lin-PG** [comment]
PASS QA 1.63.0
