### ISSUE TITLE
Updates submitted to bc211: School District and SWIS records

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#595]
Submitted the following updates to updates@bc211.ca on Dec 3, 2020 and bc211 confirmed on the same day that those updates have been made on their website. We'll need to confirm that these updates are on the latest bc211 csv dataset we receive for the next production release and also test that they show up on the app accordingly. 

(1) Kootenay Lake School District (aka School District 8): 
As per their website, the address should be: 811 Stanley Street, Nelson, B.C. V1L 1N8

(2) Delta School District  (aka School District 37): 
As per their website, the email should be: info@deltasd.bc.ca 

(3) North Vancouver School District  (aka School District 44): 
As per their website, the postal code should be V7M 2K6 (not V7M 2K5)

(4) Sunshine Coast School District: 
As per their website, the email should be questions@sd46.bc.ca 

(5) Sea to Sky School District: 
As per their website, the email should be JMorris@sd48.bc.ca

(6) Greater Victoria School District:
 As per their website, the general email should be: community@sd61.bc.ca 

(7) Alberni School District (aka School District 70): 
As per their website, Alberni School District is also called Pacific Rim School District.

(8) Mission School District  (aka Mission Public Schools; School District 75): 
As per their website, the email should be: info.sd75@mpsd.ca

(9) Settlement Workers in Schools (SWIS) Program provided by Surrey School District (aka School District 36): 
Broken link: http://www.welcomecentre.sd36.bc.ca
Should be: https://www.surreyschools.ca/welcomecentre/Pages/default.aspx 

(10) Settlement Workers in Schools (SWIS) Program provided by Richmond School District  (aka School District 38)
As per website: 
Gilmore Elementary School
8380 Elsmore Rd, Richmond, BC V7C 2A1 *We are also located on 1st Floor Reception Desk- 7811 Granville Ave (Richmond School Board)*
Phone: 604-668-6268
E-mail: swis@sd38.bc.ca

(11) Settlement Workers in Schools (SWIS) Program provided by: Vancouver School Board (VSB)  (aka School District 39)
Missing address - As per their website, the Newcomer Welcome Centre is located at 1000 East 59th Avenue, Vancouver, V5X 1Y7

(12) Settlement Workers in Schools (SWIS) Program provided by: Maple Ridge-Pitt Meadows School District  (aka School District 42)
Broken link: http://www.sd42.ca/swis-settlement-workers-schools
Should be: https://www.sd42.ca/programs/settlement-workers-schools/

(13) Settlement Workers in Schools (SWIS) Program  provided by: North Shore Multicultural Society
Broken link: http://nsms.ca/living-in-canada/north-vancouver-school-district
Should be: https://nsms.ca/workshop-type/settlement-workers-in-schools/

(14) Settlement Workers in Schools (SWIS) Program  provided by: West Vancouver School District
Broken link http://www.sd45.bc.ca/ps/swis
Should be: https://westvancouverschools.ca/resources/students/swis-settlement-workers-in-schools

(15) Settlement Workers in Schools (SWIS) Program provided by: Peace
 River North School District (aka School District 60)
The school district's website indicates that the Settlement Workers in Schools (SWIS) Program is offered; however, it's not listed as a service on bc211 website. 
Here's the contact info for the SWIS program:
10112-105 Avenue, Fort St. John, B.C., V1J 4S4
(250) 262-6027
jdrew@prn.bc.ca

(16) Settlement Workers in Schools (SWIS) Program provided by: Inter-Cultural Association (ICA) of Greater Victoria 
Broken Link: http://www.icavictoria.org/welcome-centre/youth-services/settlement-workers-in-schools
Should be: https://www.icavictoria.org/welcome-centre/youth-family-services/settlement-workers-in-schools/ 

(17) Settlement Workers in Schools (SWIS) - School District 53 and 67 provided by: South Okanagan Immigrant and Community Services (SOICS)
As per their website, the address should be 340 Ellis St, Penticton, BC V2A 4L7 (508 Main St. was the old address of SOICS' head office)

(18) Fort Nelson School District (aka School District 81) 
As per their website, email should be contact@sd81.bc.ca

(19) Stikine School District  (aka School District 87)
Remove the email address since tetzerza@sd87.bc.ca is no longer listed on the school district's website and to be consistent with other records (i.e. no email address is provided on bc211 website when there's no email available for general inquiries)

### Acceptance Criteria 
- [ ] confirm that those records are updated on the latest csv dataset we receive for next productions release
- [ ] confirm that those updated records show up on production app accordingly

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
@jparlina Kootenay Lake school district still has wrong address. These services should be on the production app now.

**Comment by deniza-pg** [comment]
BC211

(1) Kootenay Lake School District  OK
(2) Delta School OK
(3) North Vancouver School District OK
(4) Sunshine Coast School District: OK
(5) Sea to Sky School District: OK
(6) Greater Victoria School District: OK
(7) Alberni School District (aka School District 70): OK
(8) Mission School District (aka Mission Public Schools; School District 75): OK
(9) Settlement Workers in Schools (SWIS) Program provided by Surrey School District (aka School District 36): OK

**(10) Settlement Workers in Schools (SWIS) Program provided by Richmond School District (aka School District 38)  FALSE 
I expect to see the number Phone: 604-668-6268 But it is different.**

(11) Settlement Workers in Schools (SWIS) Program provided by: Vancouver School Board (VSB) (aka School District 39) OK

(12) Settlement Workers in Schools (SWIS) Program provided by: Maple Ridge-Pitt Meadows School District (aka School District 42) OK

(13) Settlement Workers in Schools (SWIS) Program provided by: North Shore Multicultural Society. OK

(14) Settlement Workers in Schools (SWIS) Program provided by: West Vancouver School District OK

(15) Settlement Workers in Schools (SWIS) Program provided by: Peace
River North School District (aka School District 60) OK

(16) Settlement Workers in Schools (SWIS) Program provided by: Inter-Cultural Association (ICA) of Greater Victoria.  OK

(17) Settlement Workers in Schools (SWIS) - School District 53 and 67 provided by: South Okanagan Immigrant and Community Services (SOICS) OK

(18) Fort Nelson School District (aka School District 81) OK

(19) Stikine School District (aka School District 87)  OK

APP:

**(1) FALSE : I expect to see the address 811 Stanley Street, Nelson, B.C. V1L 1N8 But it is different in the app.** 

(2) OK

**(3) I expect to see the postal code as  V7M 2K6 but is V7M 2K5**

(4) OK

(5) OK

(6)OK

**(7) I was expecting to see Pacific Rim School District. But it wasn't there.**

(8) OK

**(9) I was expecting to find the website :   https://www.surreyschools.ca/welcomecentre/Pages/default.aspx 
but I found
 https://www.surreyschools.ca/**

(10) Couldn't find Settlement Workers in Schools (SWIS) Program provided by Richmond School District  in the app

(11) Couldn't find with search

(12)

**Comment by deniza-pg** [comment]
cont... in app
(10)

(11)  OK

(13) I was expecting to see the longer link, but it was nsms.ca

(14) I was expecting to see the longer link but it was westvancouverschools.ca

(15)
