### ISSUE TITLE
Confirm data updates submitted to bc211 - Burnaby English Language Centre (BELC) and Powell River Immigrant Services

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-backend#596]
Submitted the two data updates below to updates@bc211.ca and bc211 confirmed that the updates were made on their website. We need to confirm that those updates are on the latest bc211 csv we receive for next production release and shows up on the production app accordingly. 

- Submitted on Oct 13, 2020 and bc211 confirmed that the record was removed from bc211 listing on the same day:
Burnaby English Language Centre (BELC) - no longer exists

- Submitted on Oct 27, 2020 and bc211 confirmed updates were made on Oct 28, 2020: 
We were informed by Kelli Henderson, Program Manager of Powell River Immigrant Services, that she'd like to update the service description as follows: `Supports the social and economic integration of newcomers who are eligible to receive services from provincially or federally-funded programs. Program serves permanent residents, refugees, temporary foreign workers, post-secondary international students with a work permit, provincial nominees who are not yet permanent residents, and recently naturalized citizens who continue to be dependent on settlement support; there may be eligibility restrictions for some services. Provides information and referral, consultation and crisis support, assisted access to services, and assistance with documents and forms. The Welcome Centre offers English language tutoring, support for LINC Online, a parents’ group and conversation club, community orientation sessions and workshops, and cultural celebrations and social events. Drop-in hours are 9:30 am to 2:00 pm Monday to Thursday; an appointment is required outside of these hours. Serves Powell River & Regional District. Funded by Immigration, Refugees and Citizenship Canada (IRCC), and Ministry of Jobs, Economic Development and Competitiveness as a BC Settlement and Integration Services (BC SIS) program. BC SIS services provided under contract to Capilano University. `

### Acceptance Criteria 
- [ ] confirm that those two updates are on the latest bc211 csv we receive for next production release 
- [ ] confirm that those two updates show up on the production app accordingly

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
@jparlina I checked that BELC no longer exists in search and that the description has been updated.

**Comment by tomy-pg** [comment]
I can confirm BELC no longer exists and `Powell River Immigrant Services'` description has been updated accordingly.
