### ISSUE TITLE
As an Anonymous user, I can filter search results so that I can easily find specific human services relevant to me

### ISSUE THREAD

**Issue by robinpuga** [pg-irc/pathways-backend#60]
From mock ups:
<img width="419" alt="screen shot 2017-08-18 at 3 24 20 pm" src="https://user-images.githubusercontent.com/2782487/29479779-18c49e98-8429-11e7-94af-8d2565001060.png">
<img width="422" alt="screen shot 2017-08-18 at 3 24 12 pm" src="https://user-images.githubusercontent.com/2782487/29479780-18ccf840-8429-11e7-97cd-423056beac52.png">
<img width="567" alt="screen shot 2017-08-18 at 3 23 56 pm" src="https://user-images.githubusercontent.com/2782487/29479782-18d26410-8429-11e7-9473-e8ca80bfd97b.png">

**Comment by PeaceGeeks** [comment]
What are the filter that I can search on? (category? sub-category? province? city? eligibility criteria? etc.)
