### ISSUE TITLE
Every topic lists itself as a "related topic"

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#609]
Open the app, go to any topic, observe that the topic itself is always listed among the three related topics. 

### Acceptance Criteria 
- [ ]  All three related topics are *different* from the topic shown in the detail page.

### Steps for QA: 
1.

**Comment by tomy-pg** [comment]
What I see is that if you go to any topic from the **Related Topics** list, that the topic will always list itself among the three related topics. 

If you click into another topic from the recommended list in the home screen, you won't see the same behaviour. This is probably a result from `componentDidUpdate` being too restrictive on when it refreshes in a topic list component.

**Comment by rasmus-storjohann-PG** [comment]
Could not reproduce, but not 100% sure

**Comment by rasmus-storjohann-PG** [comment]
Can not reproduce
