### ISSUE TITLE
Script to import MB WIN document into topics folder structure

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#611]
Source file is [here](https://docs.google.com/document/d/1EbBl0-p8VR9bDc4H4NeVa-YDAbwbCk3ilqP6RHQV1VE/edit#)

### Acceptance Criteria 
- [x] Script reads txt file as exported from current google document
- [x] Script produces output in the same folder structure as currently used for NCG content
- [x] Output from the script can be converted to a fixture using existing tool.
- [x] When importing existing newcomers guide content, the resulting topics are tagged with region:BC
- [x] When importing WIN data, the resulting topics are tagged with region:MB
- [x] Data structure can handle more than one topic with the same name, i.e. topic names are no longer assumed to be unique

**Comment by ian-lin-PG** [comment]
Manitoba topics currently show up in manitoba version of the app. Pass QA 1.66.0
