### ISSUE TITLE
Include MB data in AA deploy scripts

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#615]
## Data management
* MB WIN data will be checked into the content repo

## Preparation
* Clear and initialize PSQL database

## BC211/MB211 steps
Risk of primary key collision between the two data sets.
* Start with iCarol CSV format
* Convert to OpenReferral CSV format
* Import into the PSQL database

## Various other sets of service data
This includes library data, school data, organizations as services data. There is also here a risk of primary key collisions
* Start with iCarol CSV format
* Convert to OpenReferral CSV format
* Import into the PSQL database

## BC Newcomers' Guide / MB WIN steps
- [x] MB only: Convert from single EN txt file to folder structure (BC data is already in this folder structure). Change folder structure to contain a top level `bc` or `mb` folder, so the file path will be `../content/NewcomersGuide/bc/Chapter\ 2\ -\ Settling\ in/topics/Personal\ safety/en.Personal\ safety.md`
- [x] Change BC folder structure to have a `bc` top level folder
- [x] Change MB conversion script to produce folder structure with `mb` top level folder
- [x] Change fixture script to read the region top level folder and add corresponding attribute to each topic in fixture
- [x] MB only: Convert from single txt file in other languages to folder structure
- [x] Build fixture from folder structure, topic ids with regional prefix (bc or mb)

- [x] Avoid primary key collisions by adding `bc` and `mb` prefixes to topic identifiers. This will happen in the step that builds the fixtures...
- [x] ...as well as in the script that imports topics into the database for NLP processing.
- [x] Avoid primary key collisions by adding `bc` and `mb` prefixes to service and organization identifiers, this will happen in the conversion from iCarol CSV to the OpenReferral CSV.
- [ ] We compute related tasks using NLP, we need to ensure that no BC task is related to a MB task and vice versa
- [x] Fixture containing both BCNCG and MBWIN dataset needs to be built in one step
- [x] Each topic needs to be labelled to reflect which province it applies to, we will use taxonomy terms `region:bc` and `region:mb` for this.
- [x] It may be needed to put prefixes on the various service primary keys to avoid collisions

## Steps for QA

- [x] Run the server side prepare deploy script. Check that the script does not terminate with error. Check the produced warnings to get a good understanding of what is causing them, and suggest solutions to resolve the warnings. This work can be done by all of us in parallel by dividing the warnings between us.
- [x] Merge all PRs, tag them with the next staging version id. Build the staging app using the client side prepare deploy script.

**Comment by tomy-pg** [comment]
`Importing open referral CSV data from ..//openreferral/211/bc`
We see four different warnings:
1. `WARNING address Country field with value: All countries is invalid`
I do not think we need a solution to resolve this warning. We could likely just remove this warning.

2. By far the most frequent warning 
```
WARNING address ValidationError in row with location id "f803f8c6a5316be4ac4b2ae5d32f4c9349af6237" and address "None, None BC, CA None": ["type=LocationAddress id=None message={'__all__': ['Location address with this Location and Address type already exists.']}"]
```
There are seemingly duplicate organizations with the same "location" in the iCarol csv file we receive from BC211. In these organizations, from what I have seen there are some variances in the data. We could use more fields in `generate_location_id` to make ids more unique.

**Comment by ian-lin-PG** [comment]
This has been used in the last few releases. Passes QA when releaseing 1.70.0
