### ISSUE TITLE
Convert BC211 CSV file directly to Algolia JSON

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#633]
### Basic idea
* All source of truth data stored in CSV files or spreadsheets that will be converted to CSV files
* CSV header names match the data exported from BC211 and MB211
* Use a script to modify the CVS headers to a form that works with Algolia
* Use csvtojson to convert CSV files to json
* Import json into MongoDB, so that all sources of truth are stored in different collections in Mongo. Probably keep data from differet regions (BC, MB) in different collections.
* Denormalize the services data in Mongo using data from other collections, such as organizations, city lat/long values, recommendations, etc
* Export services data from Mongo to json, upload to Algolia
* Create different Algolia indeces for different queries, services related to a topic, services near me, etc.

### Acceptance Criteria 
- [ ] To be implemented in python/bash and use csvtojson (not csv2json!)
- [ ] Conversion of multiple input files gives output files that can be combined into a single Algolia index
- [ ] Script uses cityLatLong data to complete the lat/long attributes for services that have just a city, no address and no lat long
- [ ] Service primary keys are called "_id" consistent with mongoDb, and their values are the region + id, e.g. "bc_343223" to ensure that there are no primary key collisions between different data sets, and also that the same service will be given a consistent key that does not change with repeated conversions from the CVS data format
- [ ] Service with organization: Script adds organization attributes to services that have organizations
- [ ] Service without organization: Script produces service records that have no organization attribute
- [ ] Organization without service: Script produces a service record with the attribute of the organization
- [ ] Include manual recommendations from topics to services: Each service record contains an optional attribute of the topic ids that it would be recommended for - this piece will allow Algolia to take on the function that Django is currently filling for the app 

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
As for how MongoDB should be structured, this is not a topic I am familiar with. My only criteria is that it be easy to maintain and returns payload similar to what the current Django server returns.

We don't need to create different algolia indices, we can customize the query going into algolia to achieve similar results with much less space.

**Comment by rasmus-storjohann-PG** [comment]
This work ended up being done in its own new repository pathways-mongo. Issues are tracked there. Closing this issue.
