### ISSUE TITLE
Fix some deployment issues

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#634]
Found some issues when going through the deployment process.

### Acceptance Criteria 
- [x]  Correctly copies .env and google-services.json from deploy
- [x] Translation is not strict (we want to change this back before pushing to production, see Issue #xxx.
- [x] When importing manual recommendations, the region can optionally be given on the command line, it is added as a postfix on both topic and service primary keys.

### Steps for QA: 
1.

**Comment by ian-lin-PG** [comment]
This change has been merged for a while. Import sees no issue. Passes QA on release 1.70.0
