### ISSUE TITLE
As a Service Provider, I want all my services to be up to date with BC211.

### ISSUE THREAD

**Issue by tuckerbuchy** [pg-irc/pathways-backend#77]
We are getting out data from BC211 as a data export (as of now). This makes BC211 the authoritative source of the records we are keeping track of. These records can change as Service Managers make updates (for example, the address of a Organization could change, or they could provide a new service). 

In order for us to have up to date data, we need to sync with BC211 for these changes. 
Currently here is the proposed operations:

- At deployment, we seed out database with the current BC211 data through an export on their side.
- Periodically (say once a day) , BC211 will upload a dump of the current data set to a known location.
- Services Advisor Pathways will check for this new data dump, and sync all records accordingly. 

Further Complications:
- If we would like to have the ability to update records on our own Admin panel, this would add extra. This would be that we would be diverting from the BC211 data, and would need to sync these changes **back** to BC211. How would this work? Is this DEFINITELY in scope? 

See this diagram for a players involved: https://drive.google.com/file/d/0B6riHKIYojeGeHBfQUFLV2dxWUU/view?usp=sharing

**Comment by dylanmccall** [comment]
Does this mean that a Service Provider user's account should be linked somehow to the data we load from outside sources like BC211? We should think about how that is going to work, as there may be a number of requirements. May just be a matter of a Manager user doing that manually. If we want to do it automatically, we need to think about which fields we can use as verification.

**Comment by greggish** [comment]
FYI: 

The Ohana API does have a system for this, but it's got significant flaws. In short, it assumes that  service providers will want to go in to update their own information (not true, most of the time -- especially if there is no financial leverage) AND that if they do so, they'll do it correctly (also not true; because of both human error and also misleading information). So this can only ever be one input, and requires verification.

That said, Benetech is prototyping some new tools that include a verification process: https://github.com/benetech/LegalServicesFlorida

**Comment by dylanmccall** [comment]
Another thought here is I'm unsure whether we'd want someone to *edit* data they get from something like BC211 (as in #86), since that sounds like an authoritative source, and if they have a change, they should make it there. But there are probably some particulars. Could use some specification :)

**Comment by tuckerbuchy** [comment]
Right, thanks @dylanmccall and @greggish I'll update this ticket to have more of a description. 

@greggish interesting points on the operations of updating records. Seems to point to features we have not put a lot of thought into (reviewing the updates etc). 
From what I understand thus far, BC211 will remain the authoritative source of the data, and we will just be syncing to them. Updates that we make will be pushed out to them in the form of a report that they can review and make the changes if they see fit. This is the current recommendation from them. Sounds kind of shady, but is probably a path of least resistance as it would be hard to convince service managers to use change their process. I will send an email out to BC211 to clarify this process.

**Comment by greggish** [comment]
Sounds about right. 

That said, they use iCarol, right? This sounds v similar to the use case addressed by the project that Health Leads and iCarol are working on... just recently described in the #openapi slack channel.

**Comment by tuckerbuchy** [comment]
for reference: https://github.com/openreferral/api-specification/issues/50

**Comment by rasmus-storjohann-PG** [comment]
Keeping this story open for the sake of the interesting discussion above
