### ISSUE TITLE
Add an API endpoint that speaks JSON API and bundles service details

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-backend#92]
Our application needs the ability to ask the API for a list of services matching certain filter parameters, which will be displayed on a map. It is important that we are able to show stuff to the user as quickly as possible, so to accomplish this it will help to do as much filtering as we can on the server, and also to bundle related data in a single response.

This endpoint should return data in a format matching the [JSON API](http://jsonapi.org/) specification. It should provide list of matching service documents with the following:

 - A name, alternate name, and description.
 - A list of category names, and a separate list of which category names matched the query.
 - A url, and email (via related service at location record).
 - Other related contact details, payment info, etc.
 - A program ID. (Nullable).
 - An organization ID. (Nullable).
 - A location ID. (Nullable).

The endpoint should also return, via [*included*](http://jsonapi.org/format/#fetching-includes), a list of program documents, organization documents, and location documents matching the IDs:

 - Program documents include: id, name, alternate name.
 - Organization documents include: id, name, alternate name, description, email, url.
 - Location documents include: id, geo coordinates, description, transportation help text, physical address (via related physical address record).

**Comment by dylanmccall** [comment]
Note that, while the application will probably try talking to a single API endpoint for now, it makes sense to implement this as a collection of API endpoints. For instance, it makes perfect sense to create a friendlier location endpoint that includes a physical address property. That should just be a nested object: `{location_name: "Somewhere", physical_address: {address_1: "123 Fake Street", city: "Vancouver"}}`.

**Comment by tuckerbuchy** [comment]
@dylanmccall you can get the physical address through the `/locations/{location_id}/physical-address/` endpoint. Have you looked at the open referral endpoints?

**Comment by dylanmccall** [comment]
I have, and they're full of implementation details. Great for data transport, but we need something very different. I don't think *our* API should expose that a physical address is a separate record. Doing so costs a network operation for every location for which we want to look up a physical address (and a list of languages, and a schedule). That costs bandwidth and performance, and burdens the client with rebuilding a relational data model that already exists on the server. Asynchronously. (And poorly). It might not be *one* API operation to get everything we need, but ideally we can get it to a state where it doesn't take 5 operations to build a single popup bubble.

**Comment by dylanmccall** [comment]
I think we also need a way to create filters on the server. At the moment the API doesn't appear to provide us with a list of category names. We could build a list into the app or add an endpoint to get all categories, but that won't scale very well if we look beyond 211 data.

So we could have a format for filters that that optionally take parameters, map them to categories and other things on the server, and then the app can can display those. We would need a */filters* endpoint that returns filters along with their names and schemas.

**Comment by dylanmccall** [comment]
Closed pending some more scheming which will likely supersede this task :)
