### ISSUE TITLE
Implement an API for predefined searches with Pathway Goals

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-backend#93]
The Pathways back-end should provide a search API based on the [Human Services Data API](https://openreferral.github.io/api-specification/). We should make sure an application is able to get all the information it needs to show a service on a map, quickly, with a small number of HTTP requests. Where the existing specification doesn't fit, we should work with OpenReferral project to solve that. A light superset is okay for features that are specific to our project.

For search queries, it is likely that we will want to provide a list of filters that could change quite fluidly. So, it is good to treat them as content rather than baked in to the front-end. I described what I think that API could look like over here: https://gist.github.com/dylanmccall/2875fe98953f27a08a4d337cdb0d179c.

 * [ ] Add a set of search endpoints using the HSDA search specification. We should be able to get a result with services and related data in a single place. (Initially, return an empty set, or the first ten services. This sub-task is done as soon as the endpoint generates a correct response).
  * [ ] Implement search queries with fields listed in the request payload.
 * [ ] Future: Add a mechanism to create field filters that are stored in the database. These filters must map to database queries.
 * [ ] Future: Add a search/filters endpoint that returns a list of available query filters, and some hard-coded (or auto-generated) region filter specifications.
* [ ] Future: Change the search/filters endpoint to return filters from the database in addition to auto-generated region filters, and the search/query endpoint to understand filters that are described in the database.

**Comment by dylanmccall** [comment]
Note that region filters would just map to service areas from an HSDS data source, but it strikes me as a good idea to have the pieces aligned so we can do geo queries if needed. Placing the filter logic on the server (instead of the client querying specific fields) allows us to do exactly that.

Some of these bullet points are obviously just future-proofing, but search is pretty important to us so I think that's probably okay? I'm very open to tweaking this :)

**Comment by greggish** [comment]
I'd like to better understand your requirements and how you think they might not be compatible with HSDA. Our objectives, after all, are to make it easier for projects like yours to get up and running – with the thinking that individual implementations can add extensions and/or adapt HSDA to their particular needs, while maintaining general interoperability with the broader ecosystem. And since we're actively engaging with the questions of search and filter, feedback about what you need might help us get there in v1.2 of the spec (due in a couple of weeks).

Perhaps you can join us in Slack/Hangouts on Friday, for office hours with @kinlane?

**Comment by dylanmccall** [comment]
Sure, I'm sure we'd love to chat about them and I'll see to it that we get in touch. We need to do a bit more planning first, too, but I appreciate your proactiveness! Thinking about it, "in place" isn't a good way to go here, of course, since implementing the full API shouldn't be trouble.

 * One of my initial fears was performance. We need a front-end app that talks to this search API, and ideally we can get fast responses to the user without wasting resources. The discussion about having /everything endpoints should cover that as well, so that's a happy thing.
 * The data we handle is likely to be pretty inconsistent, so we *may* want to help with that by enabling more abstract sorts of search parameters.
 * It would be super helpful to have a mechanism by which the client can ask the server "what can I search for?" and get back a list of categories, licenses, etc. because the nature of our project means that list probably isn't a static thing. (This is most of the rationale for the filters thing).
 * There are a number of gaps in the search API spec as written, which I'm sure you know about :) Having a clearer sense of what it's supposed to do would be very reassuring.

**Comment by greggish** [comment]
Cool. Some of these seem like issues that have already been raised (and may be addressed in the upcoming v1.2 -- a couple weeks away). Some of the gaps you might help us clarify through more details on your needs. And some of this might be custom implementations that you can adapt yourselves. 

I think folks from pathways are already in our Slack team, let me know if you need an invite.

**Comment by greggish** [comment]
FYI, see kin's update here: https://github.com/openreferral/api-specification/issues/46

**Comment by dylanmccall** [comment]
Thanks @greggish! That makes lots of sense. I'll keep an eye on what comes out of that :)

**Comment by greggish** [comment]
Did you all take a look at [the Search specification that @kinlane put forth in HSDA v1.2](https://openreferral.github.io/api-specification/hsda-search/)? I wonder if it meets your needs, if you have any questions, etc.

**Comment by rasmus-storjohann-PG** [comment]
This story and https://gist.github.com/dylanmccall/2875fe98953f27a08a4d337cdb0d179c is about the kinds of stored searches that will be part of the pathways system for returning all services that will be relevant to the user solving a particular problem that forms part of one of the goals in the pathways (domain details and terminology still TBD). That kind of search will be part of some future pathway related API endpoint, not the search endpoint described here. For the search API work, see master story #163

**Comment by rasmus-storjohann-PG** [comment]
This issue contains useful discussion, however, see #163 for our plan for search API, significant parts of which is implemented.
