### ISSUE TITLE
Sprint 10 Goals (Wed, Sept 27, 2017)

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-backend#96]
- IRC/ PG discussion on requirements Friday, Sept 29
  - Update Discovery Outcomes doc with requirements collected for IRC needs
- AB documenting data model and creating diagrams 
  - Working towards an Information Architecture document
- BC211 Discussions
  - Do we have any new requests for the BC211 data before it goes out to their orgs?
  - @robinpuga: Review Tucker’s data model comparisons
- [x] @dylanmccall: Working on UI for filtering on map and listing. Needs a plan and tickets
- [x] @dylanmccall: Researching Django translation features
- [x] @dylanmccall: If we limit the record listings to just the relevant records for Immigrants and Refugees, how many records (and words) would need to be translated?
 Relevant taxonomies are documented here: https://docs.google.com/spreadsheets/d/194cUjM-dSSAP6-2EEh2dwTvVaHOIiJ79nxirTdy3caM/edit#gid=0
- [ ] @rasmus-storjohann: Story wrangling
- [ ] @rasmus-storjohann: Begin with server backend epic, putting into GitHub and tag his commits to this to start off.
- Rasmus away from this Friday until Tuesday, Oct 17th
- International Rescue Committee (IRC) Discussions
  - Following up with MOU
  - Contracting with Rey 
  - Collecting requirements and meeting their field workers

**Comment by dylanmccall** [comment]
Simple count of translatable strings belonging to the taxonomies listed [in that spreadsheet](https://docs.google.com/spreadsheets/d/194cUjM-dSSAP6-2EEh2dwTvVaHOIiJ79nxirTdy3caM/edit#gid=0):

    $ mongo 'mongodb://ds159112.mlab.com:59112/bc211'
    rs-ds159112:PRIMARY> var service_ids = new Set()
    rs-ds159112:PRIMARY> var taxonomies = db.bc211_taxonomy.find({who: {$in: ['Children', 'Workers', 'Women', 'Refugees', 'Immigrants/Ethnocultural Groups', 'Employment Insurance Recipients', 'Employers', 'Income Assistance Recipients', 'Tenants', 'Landladies/lords', 'Muslim', 'Scandinavian']}}, {service_id: true})
    rs-ds159112:PRIMARY> taxonomies.forEach(taxonomy => {
        service_ids.add(taxonomy.service_id);
    })
    rs-ds159112:PRIMARY> service_ids.size
    1154
    rs-ds159112:PRIMARY> var strings = new Array()
    rs-ds159112:PRIMARY> var services = db.service.find({id: {$in: Array.from(service_ids)}})
    rs-ds159112:PRIMARY> services.forEach(service => {
        if (service.name) strings.push(service.name);
        if (service.alternate_name) strings.push(service.alternate_name);
        if (service.description) strings.push(service.description);
    })
    rs-ds159112:PRIMARY> strings.length
    1942
    rs-ds159112:PRIMARY> strings.reduce((count, string, index) => count + string.split(' ').length, 0)
    72636

So, 1942 distinct service records, 72636 words.

**Comment by rasmus-storjohann-PG** [comment]
Is this story tracking work left to be done or can we close it?
